### PR TITLE
obsolete cutaneous Paget disease

### LINKED ISSUE #1266: [Obsolete] MONDO_0002655 cutaneous Paget disease'
**Mondo term (ID and Label)**
 MONDO_0002655 cutaneous Paget disease'

**Reason for deprecation**
duplicate

**Suggested replacement or term to consider**
MONDO_0008177	extramammary Paget disease'

### PR DESCRIPTION
**Pull request by nicolevasilevsky**
closes #1266

### CODE REVIEW

**Comment by nicolevasilevsky** [comment]
Hm, no, I don't see 'mammary Paget disease' classified under 'extrammamary Paget disease'

image

image

**Comment by nicolevasilevsky** [comment]
Was it wrong to merge these terms?
This reference suggests that extramammary Paget disease is a type of cutaneous Paget disease:
" EMPD represents 6.5% of all cutaneous Paget disease..." https://www.ncbi.nlm.nih.gov/books/NBK493224/

**Comment by cmungall** [comment]
ah ok but if you changed the ldef of mammary Paget disease to have the location zone of skin of breast (to match the text def) it would 

Look at the ldef of extrammmary PD in your screenshot. There is nothing in the logic that matches the the qualifier in the name

**Comment by nicolevasilevsky** [comment]
I had merged these because they had the same definition, but I noticed that DO  has a different def for 'cutaneous Paget disease', so I just updated that in Mondo. Closing this.

**Comment by nicolevasilevsky** [comment]
https://github.com/monarch-initiative/mondo/pull/1773

**Pull request closed without merging**
