### PR TITLE
Add new MESH xrefs (and remove some invalid ones)

### PR DESCRIPTION
**Pull request by bgyori**
While working on integrating MONDO, I found that a number of xrefs to MeSH were missing. I found a set of potential references using [Gilda](https://github.com/indralab/gilda) and curated about 190 of these using [Biomappings](https://github.com/biopragmatics/biomappings). I then added them to the OBO file here to contribute them back to MONDO. In some cases, I found that MONDO either contained invalid/obsolete MESH IDs (e.g., C562386) or I found a mapping that seemed to be a more appropriate exact match than the existing one. In these cases I removed the old incorrect xref though I tried to be very conservative and only did this in 7 cases.

I made a browseable table of the mappings I curated [here](https://github.com/biopragmatics/biomappings/blob/623af30d2ee64f36dcb147012b0ad022d5c4d8e4/src/biomappings/resources/mondo_mesh_mappings.tsv) that can be browsed to see if these make sense.

One question I had was, is the 
```
{source="MONDO:equivalentTo"}
```
annotation the right one for these xrefs? Or should I set source to something else?

### CODE REVIEW

**Comment by nicolevasilevsky** [comment]
Thank you @bgyori I will review this asap (I am just returning from vacation)

**Comment by bgyori** [comment]
Thanks, @nicolevasilevsky. I glanced at the tests and it looks like there are a couple of xrefs to MeSH where one already existed in MONDO and my PR added references to the same MESH term from another MONDO entry.
```
http://purl.obolibrary.org/obo/MONDO_0009796,MESH:C538071,http://purl.obolibrary.org/obo/MONDO_0023203
http://purl.obolibrary.org/obo/MONDO_0012382,MESH:C535310,http://purl.obolibrary.org/obo/MONDO_0017715
http://purl.obolibrary.org/obo/MONDO_0017715,MESH:C535310,http://purl.obolibrary.org/obo/MONDO_0012382
http://purl.obolibrary.org/obo/MONDO_0023203,MESH:C538071,http://purl.obolibrary.org/obo/MONDO_0009796
```
(there are just 2 cases in different permutations). Looking at the underlying entries, I think that the xrefs added in this PR are better in my view than the preexisting ones which seem inexact matches.

**Review by nicolevasilevsky — APPROVED** [review]

**Comment by bgyori** [comment]
Looks like this is all set now, could it be merged?

**Comment by nicolevasilevsky** [comment]
Yes, thanks @bgyori! I got distracted as I was traveling this week, I'll merge it now.
Thank you for your help.

**Pull request merged**
