### PR TITLE
Updating the Orphanet rare disease subset

### PR DESCRIPTION
**Pull request by matentzn**
This PR updates the rare disease subset in ORDO according to the instructions we have received from Orphanet - by simply restricting the subset to the ORDO disorder branch: 

https://www.ebi.ac.uk/ols4/ontologies/ordo/classes/http%253A%252F%252Fwww.orpha.net%252FORDO%252FOrphanet_557493?lang=en

Technically, this is achieved by looking for cross references that are part of the `ordo_disease` subset. Effectively, this is an _exact copy_ of the ordo_disease subset.

(The pipeline implemented [here](https://github.com/monarch-initiative/mondo/pull/6903/files#diff-1af575dee04c2c9efa8fadf6d31066cee642ef345885b207ae034ebb99fbc1cd) right now, but not yet ready to be merged into master; this PR here is ready)

### CODE REVIEW

**Review by twhetzel — COMMENTED** [review]
@matentzn from what I understand of the PR comment and glancing at the SPARQL query for the future pipeline, all Mondo classes with `subset: ordo_disease` should also be tagged as being in the subset `orphanet_rare` and therefore there should be the same number of Mondo classes in each. However, the number of Mondo classes in each of these subsets do not match.

- ordo_disease 6253
- orphanet_rare 6133
Why is there a difference?

**Comment by matentzn** [comment]
Great observation, thank you. I checked them and this is what came out:

For most of the cases (>96%), this was expected as we have some obsolete classes with exact mappings to the external resource which are not added to the RD subset. This list is actually very interesting in its own right, and merits in my opinion a new issue ("Improve obsoletion reasons for non grouping classes from Orphanet").

| Mondo ID      | label                                                                                                                   |
|---------------|-------------------------------------------------------------------------------------------------------------------------|
| MONDO:0017049 | obsolete hypomyelination neuropathy-arthrogryposis syndrome                                                             |
| MONDO:0034979 | obsolete peripapillary staphyloma                                                                                       |
| MONDO:0029051 | obsolete autosomal recessive nail dysplasia                                                                             |
| MONDO:0035314 | obsolete congenital tricuspid valve dysplasia                                                                           |
| MONDO:0021690 | obsolete congenital left ventricular aneurysm                                                                           |
| MONDO:0018888 | obsolete congenital cornea plana                                                                                        |
| MONDO:8000032 | obsolete malformation syndrome                                                                                          |
| MONDO:0016250 | obsolete rare adenocarcinoma of the breast                                                                              |
| MONDO:0035250 | obsolete anomalous aortic origin of the right coronary artery                                                           |
| MONDO:0009930 | obsolete pulmonary arteriovenous malformation                                                                           |
| MONDO:0018344 | obsolete periodic paralysis with transient compartment-like syndrome                                                    |
| MONDO:0017173 | obsolete non-syndromic male infertility due to sperm motility disorder                                                  |
| MONDO:0018393 | obsolete male infertility with azoospermia or oligozoospermia due to single gene mutation                               |
| MONDO:0020256 | obsolete congenital trochlear nerve palsy                                                                               |
| MONDO:0032011 | obsolete biological anomaly                                                                                             |
| MONDO:0015976 | obsolete hyper-IgM syndrome without susceptibility to opportunistic infections                                          |
| MONDO:0034028 | obsolete symptomatic form of hemochromatosis type 1                                                                     |
| MONDO:0014753 | obsolete autosomal recessive optic atrophy                                                                              |
| MONDO:0019138 | obsolete bleeding diathesis due to a collagen receptor defect                                                           |
| MONDO:0016599 | obsolete autosomal dominant secondary polycythemia                                                                      |
| MONDO:0016665 | obsolete unclassified vasculitis                                                                                        |
| MONDO:0018580 | obsolete PURA-related severe neonatal hypotonia-seizures-encephalopathy syndrome                                        |
| MONDO:0008347 | obsolete idiopathic and/or familial pulmonary arterial hypertension                                                     |
| MONDO:0016579 | obsolete dominant hypophosphatemia with nephrolithiasis or osteoporosis                                                 |
| MONDO:0026419 | obsolete isolated corpus callosum agenesis                                                                              |
| MONDO:0018532 | obsolete adenocarcinoma of liver and intrahepatic biliary tract                                                         |
| MONDO:0015305 | obsolete rare endometriosis                                                                                             |
| MONDO:0016173 | obsolete non-paraneoplastic sensory ganglionopathy                                                                      |
| MONDO:0020075 | obsolete hereditary non-syndromic obesity                                                                               |
| MONDO:0018112 | obsolete isolated scaphocephaly                                                                                         |
| MONDO:0034980 | obsolete isolated megalopapilla                                                                                         |
| MONDO:0035792 | obsolete non-syndromic anorectal malformation with rectovaginal fistula                                                 |
| MONDO:0019176 | obsolete trichorhinophalangeal syndrome type I or III                                                                   |
| MONDO:0034819 | obsolete familial intestinal malrotation                                                                                |
| MONDO:0017581 | obsolete familial infantile gigantism                                                                                   |
| MONDO:0035252 | obsolete anomalous origin of coronary artery from the pulmonary artery                                                  |
| MONDO:0034981 | obsolete optic disk pit                                                                                                 |
| MONDO:0035788 | obsolete non-syndromic anorectal malformation with anal stenosis                                                        |
| MONDO:0018598 | obsolete neonatal adrenoleukodystrophy                                                                                  |
| MONDO:0035793 | obsolete non-syndromic anorectal malformation with h-type fistula                                                       |
| MONDO:0016174 | obsolete paraneoplastic sensory ganglionopathy                                                                          |
| MONDO:0034977 | obsolete isolated microspherophakia                                                                                     |
| MONDO:0017629 | obsolete sodium channelopathy-related small fiber neuropathy                                                            |
| MONDO:0035789 | obsolete non-syndromic anorectal malformation with pouch colon                                                          |
| MONDO:8000030 | obsolete morphological anomaly                                                                                          |
| MONDO:0018114 | obsolete isolated brachycephaly                                                                                         |
| MONDO:0044331 | obsolete genetic transient congenital hypothyroidism                                                                    |
| MONDO:0034733 | obsolete cochlear nerve deficiency                                                                                      |
| MONDO:0035249 | obsolete anomalous aortic origin of the left coronary artery                                                            |
| MONDO:0035267 | obsolete quadricuspid aortic valve                                                                                      |
| MONDO:0017333 | obsolete hypomyelinating leukodystrophy with or without oligondontia and/or hypogonadism                                |
| MONDO:0014424 | obsolete congenital deficiency in alpha-fetoprotein                                                                     |
| MONDO:0018340 | obsolete hereditary isolated aplastic anemia                                                                            |
| MONDO:0016352 | obsolete idiopathic inherited hypercalciuria                                                                            |
| MONDO:0100189 | obsolete apolipoprotein A-I deficiency                                                                                  |
| MONDO:0013742 | obsolete familial mesial temporal lobe epilepsy with febrile seizures                                                   |
| MONDO:0014425 | obsolete hereditary persistence of alpha-fetoprotein                                                                    |
| MONDO:0015975 | obsolete hyper-IgM syndrome with susceptibility to opportunistic infections                                             |
| MONDO:0015837 | obsolete Unicervical bicornuate uterus                                                                                  |
| MONDO:0100229 | obsolete Heimler syndrome                                                                                               |
| MONDO:0017241 | obsolete AP4-related intellectual disability and spastic paraplegia                                                     |
| MONDO:0016589 | obsolete progressive cerebello-cerebral atrophy                                                                         |
| MONDO:0017447 | obsolete congenital absence/hypoplasia of thumb                                                                         |
| MONDO:0034024 | obsolete kyphoscoliotic Ehlers-Danlos syndrome                                                                          |
| MONDO:0016788 | obsolete genetic hyperferritinemia without iron overload                                                                |
| MONDO:0010330 | obsolete primary ciliary dyskinesia-retinitis pigmentosa syndrome                                                       |
| MONDO:0034217 | obsolete resistance to thyroid hormone due to a mutation in thyroid hormone receptor beta                               |
| MONDO:0018337 | obsolete severe neonatal lactic acidosis due to NFS1-ISD11 complex deficiency                                           |
| MONDO:0018651 | obsolete lipoyl transferase 2 deficiency                                                                                |
| MONDO:0035451 | obsolete left sided atrial isomerism                                                                                    |
| MONDO:0018574 | obsolete intellectual disability-expressive aphasia-facial dysmorphism syndrome                                         |
| MONDO:0019486 | obsolete myoclonic epilepsy of infancy                                                                                  |
| MONDO:0019174 | obsolete infantile Refsum disease                                                                                       |
| MONDO:0020548 | obsolete ocular pemphigoid                                                                                              |
| MONDO:0033947 | obsolete hereditary angioedema with normal C1Inh                                                                        |
| MONDO:0034678 | obsolete mirror-image polydactyly                                                                                       |
| MONDO:0032013 | obsolete clinical syndrome                                                                                              |
| MONDO:0018575 | obsolete microcephalic primordial dwarfism-insulin resistance syndrome                                                  |
| MONDO:0016520 | obsolete isolated Klippel-Feil syndrome                                                                                 |
| MONDO:0035448 | obsolete aprosencephaly/atelencephaly spectrum                                                                          |
| MONDO:0032014 | obsolete particular clinical situation in a disease or syndrome                                                         |
| MONDO:0015108 | obsolete rare non-syndromic intellectual disability                                                                     |
| MONDO:0035784 | obsolete non-syndromic anorectal malformation with rectovesical fistula                                                 |
| MONDO:0011794 | obsolete Dravet syndrome                                                                                                |
| MONDO:0018758 | obsolete familial patent arterial duct                                                                                  |
| MONDO:0017057 | obsolete hereditary thrombocytopenia with normal platelets                                                              |
| MONDO:0018277 | obsolete congenital muscular dystrophy with cerebellar involvement                                                      |
| MONDO:0035785 | obsolete non-syndromic anorectal malformation with vestibular fistula                                                   |
| MONDO:0035790 | obsolete non-syndromic anorectal malformation with rectal atresia                                                       |
| MONDO:0019597 | obsolete 46,XY disorder of sex development due to isolated 17,20-lyase deficiency                                       |
| MONDO:0020313 | obsolete unclassified myelodysplastic/myeloproliferative disease                                                        |
| MONDO:0016536 | obsolete autosomal recessive lymphoproliferative disease                                                                |
| MONDO:0020207 | obsolete rare isolated myopia                                                                                           |
| MONDO:0015470 | obsolete familial isolated dilated cardiomyopathy                                                                       |
| MONDO:0018222 | obsolete X-linked intellectual disability due to GRIA3 anomalies                                                        |
| MONDO:0035541 | obsolete split cord malformation type II                                                                                |
| MONDO:0035786 | obsolete non-syndromic cloacal malformation                                                                             |
| MONDO:0015848 | obsolete septate vagina                                                                                                 |
| MONDO:0020315 | obsolete unclassified myelodysplastic syndrome                                                                          |
| MONDO:0036192 | obsolete EN1-related dorsoventral syndrome                                                                              |
| MONDO:0015586 | obsolete benign familial mesial temporal lobe epilepsy                                                                  |
| MONDO:0035791 | obsolete non-syndromic anorectal malformation with rectal stenosis                                                      |
| MONDO:0015385 | obsolete external auditory canal aplasia/hypoplasia                                                                     |
| MONDO:0035581 | obsolete lethal brain and heart developmental defects                                                                   |
| MONDO:0018347 | obsolete severe intellectual disability-progressive postnatal microcephaly- midline stereotypic hand movements syndrome |
| MONDO:0018649 | obsolete cerebral visual impairment                                                                                     |
| MONDO:0035787 | obsolete non-syndromic anorectal malformation without fistula                                                           |
| MONDO:0018279 | obsolete congenital muscular dystrophy without intellectual disability                                                  |
| MONDO:0019150 | obsolete familial isolated restrictive cardiomyopathy                                                                   |
| MONDO:0010123 | obsolete absent thumb-short stature-immunodeficiency syndrome                                                           |
| MONDO:0018560 | obsolete anterior urethral valve                                                                                        |
| MONDO:0035780 | obsolete non-syndromic anorectal malformation with perineal fistula                                                     |
| MONDO:0035398 | obsolete hypomyelination of early myelinating structures                                                                |
| MONDO:0007464 | obsolete isolated distichiasis                                                                                          |
| MONDO:0035557 | obsolete intermediate atrioventricular septal defect                                                                    |
| MONDO:0019482 | obsolete dendritic cell sarcoma not otherwise specified                                                                 |
| MONDO:0035781 | obsolete non-syndromic anorectal malformation with rectourethral fistula                                                |

However, there are four odd ones:

| Mondo ID      | label                                                                                                                   |
|---------------|-------------------------------------------------------------------------------------------------------------------------|
| MONDO:0011965 | familial temporal lobe epilepsy 2                                                                                       |
| MONDO:0009349 | holoprosencephaly 1                                                                                                     |
| MONDO:0100340 | Friedreich ataxia 1                                                                                                     |
| MONDO:0024525 | Fanconi renotubular syndrome 1                                                                                          |

My assumption is for these 4, the mapping was removed recently, and this is basically just a synchronisation error.

Feel free to investigate this further with Joe, or not; for this specific PR I manually removed the four wrong subset declarations: https://github.com/monarch-initiative/mondo/commit/43bf31fb498e34f8107c716fd683cfa453223661.

I also created a QC check to ensure that this will never happen again in the future:
https://github.com/monarch-initiative/mondo/pull/7689

Seems there are a number of subsets with multiple pieces of evidence that need to be fixed (maybe 15 or so).

**Comment by twhetzel** [comment]
Ok, to summarize the subset counts:
- `ordo_disease`: 6250 --> this subset tag was removed manually from 4 Mondo classes by Nico (see [comment](https://github.com/monarch-initiative/mondo/pull/7681#issuecomment-2098193144) above)
  - I have not checked these all. @sabrinatoro can you also confirm it's ok to remove the `ordo_disease` subset from these 4?
- `orphanet_rare`: 6133 --> the reason this subset count does not match the `ordo_disease` is because 117 Mondo classes with the `ordo_disease` tag are obsolete. I don't know what the strategy is for adding these tags. Does it make sense to not maintain the `orphanet_rare` tag on the obsolete terms @sabrinatoro?

**Comment by sabrinatoro** [comment]
> can you also confirm it's ok to remove the ordo_disease subset from these 4?

In the master branch, these 4 terms do not have Orphanet x-ref. 
Why and how do they not have x-ref to orphanet but are listes here? I don't know. But these are only 4, and I don't think it is worth blocking this PR on these 4. 
We will review these as part of the orphanet alignment for the next release.

**Comment by sabrinatoro** [comment]
> Does it make sense to not maintain the orphanet_rare tag on the obsolete terms

I am not sure that I understand the question, so the following might not be relevant. (Please let me know if it doesn't answer the question)
If a term is obsolete in Mondo, it doesn't make sense (to me) that it is in a rare disease subset (it would be like saying "this term does not exist anymore, but it is in a subset"). 

That being said, I think we should review the list of terms that are considered "diseases" in orphanet, and obsoleted in Mondo. In some cases, I see why we obsoleted them. In other cases, we might review our obsoletion decision. 
This is a bigger review that can wait until after this PR is merged.

**Review by twhetzel — APPROVED** [review]
Based on the updates from Nico and Sabrina all looks good now.

**Pull request merged**
