### PR TITLE
Update imports after NCBITaxon refresh

### PR DESCRIPTION
**Pull request by matentzn**
Needs review:

- [ ] Check out branch and ensure no dangling NCBITaxon classes at the top
- [ ] Run Elk 0.5 to ensure that no unsats

### CODE REVIEW

**Comment by sabrinatoro** [comment]
@matentzn 
There is no NCBITaxon at the top, and no unsatisfiable classes 
BUT
when saving the ontology without making changes (AND checking that it is updated from master), the diff shows many changes mostly related to NCBITaxon, but also other ontology such as UBERON and GO.

(note: there is one single child that needs to be taken care of. I didn't do this because of the unexpected diff)

**Comment by matentzn** [comment]
Yes forgot about that, please do a no change normalisation PR where you load safe with protege. The labels all change

**Review by sabrinatoro — APPROVED** [review]

**Comment by sabrinatoro** [comment]
@matentzn 
After normalization, everything looks good.  I accepted the PR. Please note that I didn't merge because I wasn't 100% sure it was ok to merge (2% wondered if you needed to do anything else).

**Comment by matentzn** [comment]
Did you do a separate normalization PR or a Pr within this one here? 

I would:

- Make a separate no change normalisation PR which has all the label changes
- Merge the PR
- Merge master into this PR here
- wait qc to pass
- merge and be happy

**Comment by nicolevasilevsky** [comment]
I can do the normalization PR, I did it here:
https://github.com/monarch-initiative/mondo/pull/6649

**Review by nicolevasilevsky — APPROVED** [review]

**Pull request merged**
