### PR TITLE
rename term MONDO:0011581. addresses #577

### PR DESCRIPTION
**Pull request by nicolevasilevsky**

### CODE REVIEW

**Comment by nicolevasilevsky** [comment]
@courtneythaxton could ClinGen create a URL for your Expert Panels, that we could link to in our ontology? We could do so, if not, please let me know. Thanks!

**Comment by nicolevasilevsky** [comment]
@cmungall could we create URLs for ClinGen's expert panels? How would we go about doing so? Thanks!

**Comment by courtneythaxton** [comment]
@nicolevasilevsky @cmungall 

We do currently have URLs that distinguish each expert panel and/or working group per our ClinGen website. 

We have tried to condense the URL string and it shows affiliation numbers? Is this fine, or would you prefer smaller URLs?

For instance the Arrhythmogenic Right Ventricular Cardiomyopathy Gene Curation Expert Panel has the URL of https://www.clinicalgenome.org/affiliation/40003/

As you can see if does not have a description of the Expert panel name but rather an ID. because let's face it, that name is long. The shortened version internally is ARVC GCEP

**Comment by nicolevasilevsky** [comment]
This looks fine to me @courtneythaxton! Is this the correct URL to use for this ticket #577?

**Comment by courtneythaxton** [comment]
Yes it is!

**Pull request merged**
