### PR TITLE
add new term MONDO:0100079 and add subclass relation to MONDO:0011794…

### PR DESCRIPTION
**Pull request by nicolevasilevsky**
… and comment.

### CODE REVIEW

**Comment by nicolevasilevsky** [comment]
addresses #745

**Comment by cmungall** [comment]
Also need to resolve conflicts

**Comment by nicolevasilevsky** [comment]
it looks like this property has an extra underscore in Protege:
image

Should I fix it?

**Comment by nicolevasilevsky** [comment]
the build has passed, but for some reason it is not displaying that

**Comment by cmungall** [comment]
No, it's a fake prperty, see it doesn't have a PURL. Use the one 3 above it. I will get rid of the fake one

**Comment by cmungall** [comment]
Can you fix this?

**Comment by nicolevasilevsky** [comment]
done. The diff was a bit weird, but I don't think it caused any unintended changes

**Pull request merged**
