### PR TITLE
add new term MONDO:0100149 MYH7-related skeletal myopathy

### LINKED ISSUE #1765: [NTR/gene] MYH7-related skeletal myopathy
**Preferred gene-related syndrome label**
MYH7-related skeletal myopathy 

**Synonyms**
Myosin storage myopathy 
Laing distal myopathy 

**Definition (free text, please give PubMed ID, if applicable, in format PMID:#######)**
MYH7 related myopathy with scapuloperoneal, distal or limb-girdle muscle weakness and involving the skeletal system.
PMID:22918376
PMID:24664454
PMID:22918376

**Parent term (use [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo), or your favorite ontology browser)**
Congenital Myopathy, MONDO:0019952

**Children terms (if applicable)** Should any existing terms be re-classified as children underneath this new proposed term?

**Your nano-attribution (ORCID) or URL for a working group**
@nicolevasilevsky This MonDO ID request is coming from the ClinGen Congenital Myopathy Gene Curation Expert Panel. Let me know if I can provide any other info. Thanks!

### PR DESCRIPTION
**Pull request by nicolevasilevsky**
closes #1765

### CODE REVIEW

**Comment by nicolevasilevsky** [comment]
note to self - I asked Chris about this on Slack

**Comment by cmungall** [comment]
Although not 100% sure, 
https://rarediseases.org/rare-diseases/distal-myopathy/

_In some cases, onset of Laing distal myopathy may be early enough to cause delays in walking in affected infants. In other cases, no symptoms are apparent until the twenties. Approximately 10 years after the onset of distal muscle weakness, the proximal muscles may become mildly affected. Progression of Laing distal myopathy is extremely slow and no affected individuals have required a wheelchair even into their sixties_

Nevertheless I would just treat as one disease for now, and note the variability of onset in description

**Comment by nicolevasilevsky** [comment]
Thank you, Chris!

**Comment by nicolevasilevsky** [comment]
Thanks @cmungall. I created a new PR here:
https://github.com/monarch-initiative/mondo/pull/1812

**Pull request closed without merging**
