### PR TITLE
Update ORDO subsets

### PR DESCRIPTION
**Pull request by matentzn**
Based on @joeflack4 and @twhetzel work in https://github.com/monarch-initiative/mondo-ingest/pull/510

This commit updates the ORDO subsets in Mondo which were outdated for years. They are needed for the new ORDO RD distiniction.

### CODE REVIEW

**Comment by matentzn** [comment]
Seems to me the error is due to an unnormalised Mondo?

**Review by sabrinatoro — APPROVED** [review]

**Review by twhetzel — COMMENTED** [review]
Counts of subsets
| | gSheet | mondo-edit.obo | Diff Reason |
| --- | --- | --- | --- |
| ordo_group_of_disorders | 2016 | 2015 | MONDO:0016525 has two sources of evidence to be in this subset |
| ordo_clinical_subtype | 997 | 998 | ? |
| ordo_clinical_subtype | 6270 | 6254 | | 

NOTE: Counts from "mondo-edit.obo" includes the one "subsetdef" line

@matentzn did you do some post-processing of the content from the gSheet? I can get the diff in values if needed.

**Review by twhetzel — APPROVED** [review]
Finally was able to get the counts in the gSheet to match up with these subsets in `mondo-edit.obo`. There were more dimensions than I realized, e.g. multiple Mondo IDs in multiple subsets and multiple sources of evidence for the same subset.

**Review by twhetzel — CHANGES_REQUESTED** [review]
Counts match except for ordo_disease after merging. 
Fix as below:
MONDO:0020659 --> gSheet has ordo_disease --> needs source added back
MONDO:0034823 --> gSheet has ordo_disease --> needs subset added back
MONDO:0035547 --> gSheet has ordo_disease --> needs subset added back

**Comment by matentzn** [comment]
Amazzzzzing! Thanks for checking all that so diligently!

**Review by twhetzel — APPROVED** [review]
lgtm

**Pull request merged**
