### PR TITLE
Increasing the severity of the proxy merge test

### PR DESCRIPTION
**Pull request by matentzn**
Needs this comment to be addressed: https://github.com/monarch-initiative/mondo/issues/4167#issuecomment-995800195.

### CODE REVIEW

**Comment by nicolevasilevsky** [comment]
do we need to update this from master?

**Comment by matentzn** [comment]
No this wont work now, because of our discussion yesterday.. I still don't know why and it seriously irks me, but I guess I have no more brain cells left to deal with this.

**Comment by matentzn** [comment]
Alright, this is ready. This contains all tests discussed - fixing these will be quite a while I assume, and there is nothing really I can do to lighten the load.. Let me know if you have questions about the tests - also do not fear to actually read the SPARQL queries if you don't understand something! Maybe I made a bad call :)

**Comment by matentzn** [comment]
@nicolevasilevsky this is now ready. Any errors it flags up need to be fixed, but the tests work as expected. So once QC passes, you can merge it!

**Comment by nicolevasilevsky** [comment]
**Note to self:**
Ignore this: FAIL Rule ../sparql/qc/mondo/qc-proxy-merges.sparql: 29 violation(s)

**Comment by nicolevasilevsky** [comment]
To fix: 
FAIL Rule ../sparql/qc/mondo/qc-equivalent-to-on-deprecated.sparql: 43 violation(s)
entity,property,value

- [ ] http://purl.obolibrary.org/obo/MONDO_0000204,OMIMPS:156610,MONDO:equivalentTo
- [ ] http://purl.obolibrary.org/obo/MONDO_0000839,EFO:0003915,MONDO:equivalentObsolete
- [ ] http://purl.obolibrary.org/obo/MONDO_0005128,EFO:0001058,MONDO:equivalentTo
- [ ] http://purl.obolibrary.org/obo/MONDO_0006728,MESH:D015299,MONDO:equivalentTo
- [ ] http://purl.obolibrary.org/obo/MONDO_0006728,SCTID:2304001,MONDO:equivalentTo
- [ ] http://purl.obolibrary.org/obo/MONDO_0006728,UMLS:C0012624,MONDO:equivalentTo
- [ ] http://purl.obolibrary.org/obo/MONDO_0007149,UMLS:C1862555,MONDO:equivalentTo
- [ ] http://purl.obolibrary.org/obo/MONDO_0007464,OMIM:126300,MONDO:equivalentTo
- [ ] http://purl.obolibrary.org/obo/MONDO_0007464,Orphanet:99177,MONDO:equivalentTo
- [ ] http://purl.obolibrary.org/obo/MONDO_0007464,SCTID:95339000,MONDO:equivalentTo
- [ ] http://purl.obolibrary.org/obo/MONDO_0007468,OMIM:126410,MONDO:equivalentTo
- [ ] http://purl.obolibrary.org/obo/MONDO_0007567,OMIM:132850,MONDO:equivalentObsolete
- [ ] http://purl.obolibrary.org/obo/MONDO_0007678,OMIM:138710,MONDO:equivalentTo
- [ ] http://purl.obolibrary.org/obo/MONDO_0007801,OMIM:146400,MONDO:equivalentTo
- [ ] http://purl.obolibrary.org/obo/MONDO_0008204,OMIM:168850,MONDO:equivalentTo
- [ ] http://purl.obolibrary.org/obo/MONDO_0010086,UMLS:C0038644,MONDO:equivalentTo
- [ ] http://purl.obolibrary.org/obo/MONDO_0010254,OMIM:300129,MONDO:equivalentTo
- [ ] http://purl.obolibrary.org/obo/MONDO_0010582,OMIM:304900,MONDO:equivalentTo
- [ ] http://purl.obolibrary.org/obo/MONDO_0010582,UMLS:CN074293,MONDO:equivalentTo
- [ ] http://purl.obolibrary.org/obo/MONDO_0010804,OMIM:600048,MONDO:equivalentTo
- [ ] http://purl.obolibrary.org/obo/MONDO_0011378,OMIM:603855,MONDO:equivalentTo
- [ ] http://purl.obolibrary.org/obo/MONDO_0011750,OMIM:606960,MONDO:equivalentObsolete
- [ ] http://purl.obolibrary.org/obo/MONDO_0011794,Orphanet:33069,MONDO:equivalentTo
- [ ] http://purl.obolibrary.org/obo/MONDO_0012148,UMLS:C1837154,MONDO:equivalentTo
- [ ] http://purl.obolibrary.org/obo/MONDO_0017542,Orphanet:295185,MONDO:equivalentTo
- [ ] http://purl.obolibrary.org/obo/MONDO_0018040,Orphanet:331240,MONDO:equivalentObsolete
- [ ] http://purl.obolibrary.org/obo/MONDO_0018104,Orphanet:3460,MONDO:equivalentObsolete
- [ ] http://purl.obolibrary.org/obo/MONDO_0018797,Orphanet:477805,MONDO:equivalentTo
- [ ] http://purl.obolibrary.org/obo/MONDO_0019116,Orphanet:717,MONDO:equivalentObsolete
- [ ] http://purl.obolibrary.org/obo/MONDO_0019299,Orphanet:79385,MONDO:equivalentTo
- [ ] http://purl.obolibrary.org/obo/MONDO_0019299,UMLS:CN205933,MONDO:equivalentTo
- [ ] http://purl.obolibrary.org/obo/MONDO_0019410,UMLS:CN206138,MONDO:equivalentTo
- [ ] http://purl.obolibrary.org/obo/MONDO_0020185,Orphanet:98595,MONDO:equivalentTo
- [ ] http://purl.obolibrary.org/obo/MONDO_0020186,Orphanet:98596,MONDO:equivalentTo
- [ ] http://purl.obolibrary.org/obo/MONDO_0020187,Orphanet:98597,MONDO:equivalentTo
- [ ] http://purl.obolibrary.org/obo/MONDO_0020188,Orphanet:98598,MONDO:equivalentTo
- [ ] http://purl.obolibrary.org/obo/MONDO_0020189,Orphanet:98599,MONDO:equivalentTo
- [ ] http://purl.obolibrary.org/obo/MONDO_0020190,Orphanet:98600,MONDO:equivalentTo
- [ ] http://purl.obolibrary.org/obo/MONDO_0020191,Orphanet:98601,MONDO:equivalentTo
- [ ] http://purl.obolibrary.org/obo/MONDO_0020258,Orphanet:98688,MONDO:equivalentTo
- [ ] http://purl.obolibrary.org/obo/MONDO_0024248,SCTID:34630004,MONDO:equivalentTo
- [ ] http://purl.obolibrary.org/obo/MONDO_0033550,OMIM:618979,MONDO:equivalentTo
- [ ] http://purl.obolibrary.org/obo/MONDO_0033571,OMIM:619030,MONDO:equivalentTo

**Comment by nicolevasilevsky** [comment]
Need to fix:

FAIL Rule ../sparql/qc/mondo/qc-proxy-merges.sparql: 29 violation(s)
entity,property,value

- [ ] http://purl.obolibrary.org/obo/MONDO_0002010,Orphanet:323,http://purl.obolibrary.org/obo/MONDO_0010297 - @matentzn this is not actually a proxy merge. Orphanet:323 is a MONDO:subClassOf on MONDO_0010297

- [ ] http://purl.obolibrary.org/obo/MONDO_0002010,Orphanet:323,http://purl.obolibrary.org/obo/MONDO_0010316
- [ ] http://purl.obolibrary.org/obo/MONDO_0002010,Orphanet:323,http://purl.obolibrary.org/obo/MONDO_0010318
- [ ] http://purl.obolibrary.org/obo/MONDO_0002010,Orphanet:323,http://purl.obolibrary.org/obo/MONDO_0010366
- [ ] http://purl.obolibrary.org/obo/MONDO_0002010,Orphanet:323,http://purl.obolibrary.org/obo/MONDO_0010398
- [ ] http://purl.obolibrary.org/obo/MONDO_0002010,Orphanet:323,http://purl.obolibrary.org/obo/MONDO_0010590
- [ ] http://purl.obolibrary.org/obo/MONDO_0007105,UMLS:C1862937,http://purl.obolibrary.org/obo/MONDO_0010857
- [ ] http://purl.obolibrary.org/obo/MONDO_0008073,OMIM:603860,http://purl.obolibrary.org/obo/MONDO_0008264
- [ ] http://purl.obolibrary.org/obo/MONDO_0008073,OMIM:609886,http://purl.obolibrary.org/obo/MONDO_0008264
- [ ] http://purl.obolibrary.org/obo/MONDO_0008073,Orphanet:209886,http://purl.obolibrary.org/obo/MONDO_0000608
- [ ] http://purl.obolibrary.org/obo/MONDO_0008863,Orphanet:101022,http://purl.obolibrary.org/obo/MONDO_0020747
- [ ] http://purl.obolibrary.org/obo/MONDO_0009025,UMLS:C2936861,http://purl.obolibrary.org/obo/MONDO_0006657
- [ ] http://purl.obolibrary.org/obo/MONDO_0010114,Orphanet:93275,http://purl.obolibrary.org/obo/MONDO_0017042
- [ ] http://purl.obolibrary.org/obo/MONDO_0010920,MESH:C537772,http://purl.obolibrary.org/obo/MONDO_0019780
- [ ] http://purl.obolibrary.org/obo/MONDO_0011891,OMIM:611277,http://purl.obolibrary.org/obo/MONDO_0018214
- [ ] http://purl.obolibrary.org/obo/MONDO_0012912,Orphanet:665,http://purl.obolibrary.org/obo/MONDO_0007078
- [ ] http://purl.obolibrary.org/obo/MONDO_0012912,Orphanet:665,http://purl.obolibrary.org/obo/MONDO_0012911
- [ ] http://purl.obolibrary.org/obo/MONDO_0014225,Orphanet:447792,http://purl.obolibrary.org/obo/MONDO_0018650
- [ ] http://purl.obolibrary.org/obo/MONDO_0015459,MESH:C538339,http://purl.obolibrary.org/obo/MONDO_0005375
- [ ] http://purl.obolibrary.org/obo/MONDO_0015459,MESH:C538339,http://purl.obolibrary.org/obo/MONDO_0006060
- [ ] http://purl.obolibrary.org/obo/MONDO_0016239,UMLS:C0010690,http://purl.obolibrary.org/obo/MONDO_0018467
- [ ] http://purl.obolibrary.org/obo/MONDO_0018104,Orphanet:3460,http://purl.obolibrary.org/obo/MONDO_0010201
- [ ] http://purl.obolibrary.org/obo/MONDO_0018216,DOID:0070076,http://purl.obolibrary.org/obo/MONDO_0012496
- [ ] http://purl.obolibrary.org/obo/MONDO_0018650,Orphanet:447792,http://purl.obolibrary.org/obo/MONDO_0014225
- [ ] http://purl.obolibrary.org/obo/MONDO_0019567,Orphanet:90309,http://purl.obolibrary.org/obo/MONDO_0007522
- [ ] http://purl.obolibrary.org/obo/MONDO_0020578,NCIT:C114830,http://purl.obolibrary.org/obo/MONDO_0100471
- [ ] http://purl.obolibrary.org/obo/MONDO_0023129,UMLS:C2931416,http://purl.obolibrary.org/obo/MONDO_0008163
- [ ] http://purl.obolibrary.org/obo/MONDO_0100133,UMLS:C2936907,http://purl.obolibrary.org/obo/MONDO_0100224
- [ ] http://purl.obolibrary.org/obo/MONDO_0100471,NCIT:C114830,http://purl.obolibrary.org/obo/MONDO_0020578

**Comment by nicolevasilevsky** [comment]
qc-obsolete-equivalent-on-non-deprecated.sparql: 290 violation(s)
_I added this to the QC call agenda to discuss_

**Comment by matentzn** [comment]
Ok we didn't fix all the cases, but it reduced them by more than half! I will continue working on the slurping pipeline once this is done.  Thank you @nicolevasilevsky.

**Review by nicolevasilevsky — APPROVED** [review]

**Comment by matentzn** [comment]
I just cannot believe you finished this all yesterday. I am so thankful and frankly impressed you slotted this in - major major step forward!! Thank you!

**Pull request merged**
