### PR TITLE
update odk version to 1.5.3

### PR DESCRIPTION
**Pull request by twhetzel**
closes https://github.com/monarch-initiative/mondo/issues/8288

@sabrinatoro - a mock mondo release should be done to test this update to ODK v1.5.3 before merging this branch

### CODE REVIEW

**Comment by sabrinatoro** [comment]
@twhetzel should this be merged for this upcoming release? Can we merge after the November release instead? There won't be enough time for a mock release before then.

**Comment by twhetzel** [comment]
I missed your comment. It's fine to do after the release :)

**Review by sabrinatoro — APPROVED** [review]
It looks good to me-looks simple, however if something more should be done, I wouldn't know :-)

**Comment by twhetzel** [comment]
@sabrinatoro as long as a mock release still works then all should be good.

I have another ticket to update the ODK version in the GH Action so I'll aim to do that today as well

**Pull request merged**
