### PR TITLE
Issue 641

### PR DESCRIPTION
**Pull request by nicolevasilevsky**
add superclass assertions for 'syndromic oculocutaenous albinism and remove equivalence axiom. Addresses #641

@cmungall I'm not sure if this is the proper approach - see #641.

### CODE REVIEW

**Comment by nicolevasilevsky** [comment]
@cmungall the travis jobs keep timing out - not sure if there are actual errors with this build? Could you please check? Thanks!

**Comment by cmungall** [comment]
sorry, can you and Shahim look into this?

>

**Comment by nicolevasilevsky** [comment]
see #646

**Comment by nicolevasilevsky** [comment]
@cmungall I think we should revise the text def, is it okay if we just use the text def from orphanet?

Oculocutaneous albinism (OCA) describes a group of inherited disorders of melanin biosynthesis characterized by a generalized reduction in pigmentation of hair, skin and eyes and variable ocular findings including nystagmus, reduced visual acuity and photophobia. Variants include OCA1A (the most severe form), OCA1B, OCA1-minimal pigment (OCA1-MP), OCA1-temperature sensitive (OCA1-TS), OCA2, OCA3, OCA4, OCA5, OCA6 and OCA7.

https://www.ebi.ac.uk/ols/ontologies/ordo/terms?iri=http%3A%2F%2Fwww.orpha.net%2FORDO%2FOrphanet_55

**Comment by cmungall** [comment]
'acute disease'
and ('disease has location' some liver)

This includes any acute disease in the liver, acute liver failure is more specific

**Comment by cmungall** [comment]
there is an argument for making a triad here (acute, chronic, agnostic), but this should be checked if this is clinically meaningful

this suggests its not unreasonable:
https://en.wikipedia.org/wiki/Liver_failure

**Comment by cmungall** [comment]
> Oculocutaneous albinism (OCA) describes a group of inherited disorders of melanin biosynthesis characterized by a generalized reduction in pigmentation of hair, skin and eyes and variable ocular findings including nystagmus, reduced visual acuity and photophobia. Variants include OCA1A (the most severe form), OCA1B, OCA1-minimal pigment (OCA1-MP), OCA1-temperature sensitive (OCA1-TS), OCA2, OCA3, OCA4, OCA5, OCA6 and OCA7.

That's (nonsyndromic) OCA

This PR is about "syndromic OCA"

I will merge this for now, but will you make a new ticket for doing some additional tidying here?

I recommend getting some definitions from this
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2211462/

see particularly differential diagnosis

**Pull request merged**
