### PR TITLE
Add QC check and report for ClinGen labels

### PR DESCRIPTION
**Pull request by matentzn**
@sabrinatoro found out during curation that there are some Mondo terms with multiple ClinGen labels. We already know from #7027 that there were times when ClinGen labels made it into the curation pipeline which where not exact.

This PR

1. Adds a QC check to ensure that there are Mondo terms with multiple ClinGen labels and non non-exact ClinGen labels.
2. Adds a report to generate all current ClinGen labels as a nice table

### CODE REVIEW

**Review by joeflack4 — APPROVED** [review]

**Comment by sabrinatoro** [comment]
@matentzn This looks good to me, but it appears that the QC fail because the new QC work. I guess we need to wait for ClinGen to review the list we shared with them when we met (Wed, Feb 7th). 
Is this a correct assessment of the state of this PR?

**Review by sabrinatoro — APPROVED** [review]

**Comment by matentzn** [comment]
Yes, they need to provide fixes for the 26 conflicts..

**Comment by matentzn** [comment]
@sabrinatoro can you follow up with ClinGen when they plan to supply the fixes?

**Comment by matentzn** [comment]
@twhetzel I assigned this PR to you as you voiced interest in manually fixing the 25 clingen conflicts.

**Comment by twhetzel** [comment]
Without tickets/PRs on the latest Mondo release board, it's longer before I see these. Is there still something to be done here or is any work in this PR now included in https://github.com/monarch-initiative/mondo/pull/6903?

**Comment by matentzn** [comment]
The thing that needs to be done on this PR is to fix the QC, i.e. fixing the ClinGen preferred labels. I thought you mentioned you were going to do this because there are few? See https://github.com/monarch-initiative/mondo/issues/7630

**Comment by twhetzel** [comment]
Adding my Slack comment here: 
Are we in agreement these Mondo terms that have >1 synonym annotated with `CLINGEN_LABEL` can be fixed by reviewing the ClinGen web site to see what "Name" they list on their site and then make sure that this is the synonym in Mondo with the CLINGEN_LABEL?

For example, the error line for:
http://purl.obolibrary.org/obo/MONDO_0014564,congenital bile acid synthesis defect 5,ABCD3 congenital bile acid synthesis defect 
would have "congenital bile acid synthesis defect 5" as the CLINGEN_LABEL based on the ClinGen web site page for: https://search.clinicalgenome.org/kb/conditions/MONDO:0014564

**Comment by twhetzel** [comment]
I merged `master` into this branch since there was a Mondo release earlier. Now there are 54 violation(s) of the "qc-clingen.sparql" qc check.

**Review by twhetzel — APPROVED** [review]

**Pull request merged**
