### PR TITLE
added obsoletion protection

### PR DESCRIPTION
**Pull request by sabrinatoro**
I have received a few requests to remove some terms from the obsoletion list. I am still reviewing these requests. In the meantime, I went ahead and set up the basis to deal with "protection for obsoletion". 
In this PR, I 
- created a new AP: "obsoletion_protected"
- used this AP for a "in subset" annotation on the term to protect from obsoletion
- I removed all the "obsoletion candidate" information
- Request to protect the term from obsoletion is in the GH issue already on the term. 

@twhetzel @matentzn @nicolevasilevsky 
Please take a look and give your ok with this new subtype. 
We can set up a QC check at a later time.

### CODE REVIEW

**Review by matentzn — COMMENTED** [review]
I like the concept - can we add an "obsoletion protection reason" as a source on the subset, like:

```
subset: obsoletion_protected {source="MONDO:CLINGEN"}
```

**Comment by sabrinatoro** [comment]
> can we add an "obsoletion protection reason" as a source on the subset

I was thinking about it, but I wasn't sure what to put in (I didn't want to add a person's orcid). I think the existing MONDO sources (e.g. MONDO:CLINGEN) or a PMID should work.
I will add it! Great thought @matentzn

**Comment by sabrinatoro** [comment]
@matentzn I created the sparql query for the QC check, and I tested it successfully(it reported a term that had both obsoletion-candidate and obsoletion-protected tags).
I don't remember what else (if anything) should be done to make sure that this QC is added to our regular QC checks.

**Comment by nicolevasilevsky** [comment]
I think this sounds great @sabrinatoro, thanks for implementing this.

**Review by matentzn — APPROVED** [review]
Looks great!

**Comment by sabrinatoro** [comment]
@twhetzel do you want to take a look at this before it is merged?

**Review by twhetzel — APPROVED** [review]
lgtm

**Comment by twhetzel** [comment]
Looks like all the comments were addressed so I will merge.

**Pull request merged**
