### PR TITLE
add new terms monogenic and polygenic

### LINKED ISSUE #4126: [NTR] monogenic and polygenic
**Preferred term label:**
1. monogenic
2. polygenic

**Definition (free text, please give PubMed ID, if applicable, in format PMID:#######)**
1. A characteristic of a disease in which the cause of the disease is a variation in a single gene.
2. A characteristic of a disease in which the cause of the disease is a variation in two or more genes.

**Parent term (use [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo), or your favorite ontology browser)**
MONDO_0021149 'genetic vs non-genetic etiology'

### PR DESCRIPTION
**Pull request by nicolevasilevsky**
add term monogenic intellectual disability

close #4126
close https://github.com/monarch-initiative/mondo/issues/2042

### CODE REVIEW

**Comment by nicolevasilevsky** [comment]
open question - how should we go about axiomatizing the monogenic ID children so we get autoclassification?

**Comment by cmungall** [comment]
Can you link to the previous discussion we had about monogenic disease >1yr ago? I thought we decided against pre-coordinating these? If we add what is our strategy for completeness?

**Comment by nicolevasilevsky** [comment]
I think these are the tickets @cmungall:
https://github.com/monarch-initiative/mondo/issues/1758
https://github.com/monarch-initiative/mondo/issues/1495
https://github.com/monarch-initiative/mondo/issues/722

I created this PR because of this open ticket:
#2042

**Comment by nicolevasilevsky** [comment]
Upon discussion at the Mondo curator call, we decided we will not add terms for monogenic vs polygenic.

**Pull request closed without merging**
