### PR TITLE
Add excluded subclass of assertions for ICD10

### PR DESCRIPTION
**Pull request by matentzn**
This is a test, but real, PR which adds 47 "excluded subclass of" assertions from ICD10CM. 

The original table can be seen here: https://github.com/monarch-initiative/mondo-ingest/blob/8e9ca4be6b9623ddf715e3426954070416fa9eac/src/ontology/reports/icd10cm.subclass.added.robot.tsv

@nicolevasilevsky volunteered to take a first look. As this is the first PR of its kind, we should be a bit critical:

1. Should the subclass axiom really be excluded?
2. Is it true that the subclass axiom is not in Mondo, neither asserted nor logically implied?
3. Is it true that the subclass assertion is, indeed, in ICD10CM?

We should at the very least to some spot checking, but I feel rigour will pay off, at least for the first PR.

### CODE REVIEW

**Comment by nicolevasilevsky** [comment]
Sounds good, I am working on this, I started a [spreadsheet](https://docs.google.com/spreadsheets/d/1Fz9renG5Q2w5P3IRqB-r8Kd7CqHDa0e3C3vHDbD0VAM/edit#gid=0)

**Comment by matentzn** [comment]
🚀 🚀 🚀 🚀 🚀 This is fantastic work @nicolevasilevsky amazing!

Can we discuss during next 1:1 or tech call?

**Comment by nicolevasilevsky** [comment]
yes!

**Comment by twhetzel** [comment]
If this is work that I will eventually be a part of as we transition tech tasks I would like to be on the call :)

Also, @nicolevasilevsky what is the source you are using to view ICD10CM? 

And what criteria is being used whether the subclass axiom should be excluded? I was wondering about this for example because I thought that for: 
`MONDO:0000984	thalassemia	MONDO:0003664	ICD10CM:D56	ICD10CM:D55-D59	hemolytic anemia	yes`
that "thalassemia" is a kind of "hemolytic anemia".

**Comment by matentzn** [comment]
@nicolevasilevsky lets push discussion to tech call!

**Comment by twhetzel** [comment]
Having the discussion on the tech call sounds great! Keep in mind the next tech call that we will all be available for (Nico, Nicole, Trish) is not until Feb 2.

**Comment by nicolevasilevsky** [comment]
@matentzn I am done reviewing this [spreadsheet](https://docs.google.com/spreadsheets/d/1Fz9renG5Q2w5P3IRqB-r8Kd7CqHDa0e3C3vHDbD0VAM/edit#gid=0).

**Comment by nicolevasilevsky** [comment]
note: the PR to add new superclasses (https://github.com/monarch-initiative/mondo/pull/7332) is merged

**Comment by nicolevasilevsky** [comment]
Conclusion: for now we will create a blanket 'exclude subclass of' for everything and add a 'not verified' tag, and as we curators should keep an eye out for these 'not verified' tags and review them if we come across them during other work.

closing this.

**Pull request closed without merging**
