### PR TITLE
Add Nando Xrefs

### PR DESCRIPTION
**Pull request by matentzn**
Replaces https://github.com/monarch-initiative/mondo/pull/7760

### CODE REVIEW

**Comment by sabrinatoro** [comment]
@matentzn who is https://orcid.org/0000-0002-0170-10562 ?
It doesn't look like ORCID recognize that ID (there are one too many digit in the number)

**Comment by sabrinatoro** [comment]
@matentzn I figured out the ORCIDS. The current one are not correct. They should be:
https://orcid.org/0000-0002-0170-9172 - Toyofumi Fujiwara
https://orcid.org/0000-0003-0011-764X - TAKATSUKI Terue

**Comment by matentzn** [comment]
Lol, was a drag down error in Google sheets.. Fixed now.

**Review by sabrinatoro — APPROVED** [review]
I approve and merge this PR. Thank you @matentzn

**Pull request merged**
