### PR TITLE
Do not merge: add mondo-logos folder

### PR DESCRIPTION
**Pull request by nicolevasilevsky**
add new folder that contains mondo logos

### CODE REVIEW

**Comment by nicolevasilevsky** [comment]
@jmcmurry and @nlharris do we want to add a folder to this repo that contains all the mondo logos?

**Comment by nlharris** [comment]
> @jmcmurry and @nlharris do we want to add a folder to this repo that contains all the mondo logos?

I think this is where they should be--but once they're added here, @jmcmurry should probably delete her folder so we don't have two copies floating around getting out of sync.

**Comment by jmcmurry** [comment]
It is hard for me to keep track of logos if they're not in my
closed-illustrations repo. Logos often need to be assembled in different
formats for presentations that reference multiple projects.
May I suggest that instead of moving the logos to their respective
locations, we keep a logo.txt file here in the mondo repo with a URL to
where to find them in my logos directory?
Apologies it is just that since I'm the only one committing to the logos
and usually, the one who needs to access them for presentations it is
easier than looking in 8 different places.
Having said this, this "shared file across repos" is a problem not unique
to us; there exist fancier workarounds
<https://stackoverflow.com/questions/15844542/git-symlink-reference-to-a-file-in-an-external-repository/27770463#27770463>
should you decide you really want to be able to use the latest logos
programmatically.

>

**Comment by nlharris** [comment]
> keep a logo.txt file here in the mondo repo with a URL to where to find them in my logos directory?

That seems reasonable to me. No need to get super-fancy.

**Comment by nicolevasilevsky** [comment]
Sounds good to me too. I will close this PR.

**Pull request closed without merging**
