### PR TITLE
Expert review: add comments to connective tissue terms

### PR DESCRIPTION
**Pull request by nicolevasilevsky**
[spreadsheet](https://docs.google.com/spreadsheets/d/1VOiPTk03NeF4nGRZ198jQH978UCxNAvb/edit#gid=1842141638)

ROBOT merge template ROBOT Reviewer-Curator Agree - Leave:
`sh run.sh make TEMPLATE_URL="https://docs.google.com/spreadsheets/d/e/2PACX-1vQwbBXJPMisOhwx9Pbr1ekXVxF_Q7WvfnJUNycgTmPwBW_FjksvYsyoTAwWwBflpQ/pub?gid=298440223&single=true&output=tsv" merge_template -B`

ROBOT merge template ROBOT Reviewer-Leave Curator-Stay:
`sh run.sh make TEMPLATE_URL="https://docs.google.com/spreadsheets/d/e/2PACX-1vQwbBXJPMisOhwx9Pbr1ekXVxF_Q7WvfnJUNycgTmPwBW_FjksvYsyoTAwWwBflpQ/pub?gid=1295833230&single=true&output=tsv" merge_template -B`

### CODE REVIEW

**Comment by sabrinatoro** [comment]
@nicolevasilevsky 
The following to do is missing
- [ ]  remove parents that are in the connective tissue disease branch ("Reviewer-Leave Curator-Stay" Tab)

Otherwise, the comments have been added correctly. 
Thank you.

**Comment by nicolevasilevsky** [comment]
got it.

These terms are classified as 'connective tissue disorders' because of the parent 'autoinflammatory syndrome'.

I can exclude this parent from these terms (and in some cases, the terms will need to be reclassified) but I am not sure if this is the best approach, for example, MONDO:0957405	granulomatous autoinflammatory syndrome of childhood seems to make sense as a child of 'autoinflammatory syndrome'.

Rather, i wonder if we should reconsider the classification of 'autoinflammatory syndrome'. It is a child of 'rheumatic disorder', which is a child of 'connective tissue disorder'. I wonder if rheumatic disorder should be a child of 'connective tissue disorder'? This comes from DO and MESH.

The [CDC definition](https://www.cdc.gov/arthritis/communications/features/rheumatic-diseases-and-pain.html#:~:text=Rheumatic%20disease%20is%20an%20umbrella,that%20mainly%20affect%20the%20joints).) of rheumatic disorder is more broad:
Rheumatic disease is an umbrella term that refers to arthritis and several other conditions that affect the joints, tendons, muscle, ligaments, bones, and muscles (arthritis refers to disorders that mainly affect the joints).

Or maybe 'autoinflammatory syndrome' should not be a child of 'rheumatic disorder'? This comes from Orphanet.

**Comment by sabrinatoro** [comment]
Addresses #6742

**Comment by sabrinatoro** [comment]
I didn't realize that 'autoinflammatory syndrome' is considered a 'connective tissue disorder'.
I agree, we should review the definition and classification of 'rheumatic disorder' instead, and this will solve this issue.

Let's create a new GH issue to review this, and disregard the removal of the parents for now.
Thank you for catching this! 



auto

**Review by sabrinatoro — APPROVED** [review]

**Pull request merged**
