### PR TITLE
add new term MONDO:0100176 AP-4 deficiency syndrome

### LINKED ISSUE #1729: New Term Request: AP-4 deficiency syndrome
Preferred term label: AP-4 deficiency syndrome

Synonyms: None

Definition (free text, please give PubMed ID, if applicable, in format PMID:#######): The term "AP-4 deficiency syndrome" is often used in literature to describe genetic disorders associated with the "AP4 genes", AP4B1, AP4E1, AP4M1, and AP4S1. The phenotypes observed in individuals with genetic variants in these genes are often complex and include ID, spastic paraplegia, microcephaly, brain abnormalities, and seizures. The ClinGen ID/Autism GCEP would like to request the term "AP-4 deficiency syndrome" to encompass the complexity of phenotypes associated with variants in these four genes. PMIDs: 30543385, 29193663, 32171285, 29430868

Parent term (use [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo), or your favorite ontology browser): I have recently requested a new term "intellectual disability and spastic paraplegia" (ref #: #1728) and when this is created, this will be the parent term.

Children terms (if applicable) Should any existing terms that should be moved underneath this new proposed term?: None

Your nano-attribution (ORCID)
The ClinGen ID/Autism GCEP

### PR DESCRIPTION
**Pull request by nicolevasilevsky**
closes #1729

### CODE REVIEW

**Comment by cmungall** [comment]
I'm looking to see if the complex exists in GO etc

I see Reactome has it:
https://reactome.org/content/detail/R-HSA-5229123

**Comment by cmungall** [comment]
@nicolevasilevsky can you make a PRO ticket request and link here?

Until we have this I think we define this as the union of the 4 children. Do you know how to do that?

Also we should add a DP for this case, maybe @matentzn can help

**Comment by nicolevasilevsky** [comment]
https://github.com/PROconsortium/PRoteinOntology/issues/196

**Comment by nicolevasilevsky** [comment]
> Until we have this I think we define this as the union of the 4 children. Do you know how to do that?

No, I don't.

**Comment by matentzn** [comment]
I can help you with that in our next meeting, but usually, UNION of the 4 children means you say:

- `Term owl:equivalentTo child1 or child2 or child3 or child4`

you could go a step further and say:

- `Term x: owl:disjointUnionOf (chil1, child2, child3)`, but I think just do the normal one.

**Comment by matentzn** [comment]
(Aside: I am not sure ELK can handle those axioms; if you want the children to appear under parent just using the UNION axiom, we need to do more work, at least I think so..)

**Comment by nicolevasilevsky** [comment]
@matentzn when I check out this branch, I don't see this class in the file. Can we look at this when we meet?

Also, PRO already filled my term request!

**Comment by matentzn** [comment]
Lets do this either today during the tech call or tomorrow during our face2face.

**Comment by nicolevasilevsky** [comment]
@cmungall - Ready for your re-review
These are my changes:
1) add union equiv axiom  ('hereditary spastic paraplegia 50' or 'hereditary spastic paraplegia 51' or 'hereditary spastic paraplegia 47' or 'hereditary spastic paraplegia 52') and now these terms are inferred to be children
2) requested new term to PR, and the term request was filled
3) added the new PR to Mondo (it is not released yet)
4) added subclassOf axiom: 'disease has basis in dysfunction of' some PR_000050388
(note- we get 'disease' inferred as a parent)

**Pull request merged**
