### PR TITLE
Fix issue #3382

### PR DESCRIPTION
**Pull request by Vineyardintern**
Adds new term per issue #3382

### CODE REVIEW

**Comment by matentzn** [comment]
@Vineyardintern I think you still need to run `make imports/hgnc_import.owl`, right? Or am I mistaken? You have added the term to the termfile, which is correct, but the import has not been reloaded.

**Comment by matentzn** [comment]
(By the way, the fact that the QC checks do not pass have nothing to do with you - I brought it to the Mondo teams attention @nicolevasilevsky @sabrinatoro )

**Comment by Vineyardintern** [comment]
Very strange. All of the edits I made were in my mondo-edit.owl file and I could clearly see them in Protege but they did not appear in the diff and did not make it into the commit. I think I just need to start from scratch.

**Comment by matentzn** [comment]
We will get to the bottom of this! Can you share the output of `git status` while being in odk in mondo directory?

**Comment by nicolevasilevsky** [comment]
@matentzn Daniel and I are going to meet tomorrow to try to troubleshoot too.

**Pull request closed without merging**
