### PR TITLE
Proposal for cancer reclassification

### PR DESCRIPTION
**Pull request by sabrinatoro**
Addresses #6533

### CODE REVIEW

**Review by cmungall — APPROVED** [review]

**Comment by sabrinatoro** [comment]
@nicolevasilevsky @cmungall  (though Chris has already approved :-) ) 
Please take a look at this PR (with more explanation about the changes [here](https://github.com/monarch-initiative/mondo/issues/6533)).
This reclassification will be needed for [ClinGen request](https://github.com/monarch-initiative/mondo/issues/6515)-coming up next, to make sure that this plan works.

**Review by nicolevasilevsky — APPROVED** [review]
this looks good to me. It will be great to get the expert advice, this is certainly a tricky area.

**Comment by sabrinatoro** [comment]
I updated the logical definition for "hereditary neoplastic syndrome" to be
'inherited disease susceptibility'
 and ('predisposes towards' some neoplasm)

This brought a lot of "cancer susceptibility" into "cancer predisposition" branch, which was requested by ClinGen

@cmungall @nicolevasilevsky do you see any reason why it is not a good idea to do so (or why it is wrong to do so)?

And I agree, we should ask experts about this! We will definitely run this by the ClinGen team, but we should have a bigger discussion about it... at one point.

**Comment by nicolevasilevsky** [comment]
this  looks good to me, all the terms that were auto-classified make sense.

**Comment by sabrinatoro** [comment]
This PR was approved by Chris and Nicole, but the merging is still blocked. I am bypassing the branch protections and merging.

**Pull request merged**
