### PR TITLE
Issue 500

### PR DESCRIPTION
**Pull request by nicolevasilevsky**
capitalized label for https://github.com/monarch-initiative/mondo/issues/500

### CODE REVIEW

**Comment by nicolevasilevsky** [comment]
@cmungall I attempted to import the gene class (SLC10A7), and I added a logical def for the term MONDO:0100068. Please let me know if there are any issues.

**Comment by cmungall** [comment]
I don't see changes in the logic def or text def?

**Comment by nicolevasilevsky** [comment]
@cmungall look on this PR: https://github.com/monarch-initiative/mondo/pull/584

**Comment by nicolevasilevsky** [comment]
I am going to close this PR and create a new PR to address #500 (to capitalize the label).

**Pull request closed without merging**
