### PR TITLE
Add restrictive pulmonary disease

### LINKED ISSUE #3165: [NTR] restrictive pulmonary disease
**Preferred term label:**
restrictive pulmonary disease

**Synonyms**
restrictive lung disease 
NCIT:C91762 (exact synonym)

**Definition (free text, please give PubMed ID, if applicable, in format PMID:#######)**
Decreased lung volume and inadequate ventilation due to parenchymal lung disorders (e.g., interstitial pulmonary fibrosis) or extrapulmonary disorders (e.g., scoliosis). Patients present with shortness of breath and cough. NCIT:C91762

**Parent term (use [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo), or your favorite ontology browser)**
lung disease MONDO:0005275

**Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

### PR DESCRIPTION
**Pull request by kallia-p**
fixes #3165

### CODE REVIEW

**Comment by nicolevasilevsky** [comment]
@kallia-p your preferences are not set up correctly. I think I fixed this here, but please open Protege, and go to file-> preferences, and make sure the creator property is:
http://www.geneontology.org/formats/oboInOwl#created_by

See screenshot below:

image

**Comment by nicolevasilevsky** [comment]
For future reference, there are instructions here on how to set up Protege:
https://oboacademy.github.io/obook/lesson/contributing_to_obo_ontologies/#setup

**Comment by kallia-p** [comment]
@nicolevasilevsky Hi Nicole, thanks for fixing it. This is a screenshot of my preferences and they are identical to yours. Was this the only PR today that you've found this?

image

**Comment by nicolevasilevsky** [comment]
Oh, you are right! I'm not sure why the wrong annotation property was used then. The same problem exists in PR https://github.com/monarch-initiative/mondo/pull/3720

**Review by nicolevasilevsky — APPROVED** [review]

**Comment by nicolevasilevsky** [comment]
This looks good @kallia-p. Thanks for adding all the synonyms and xrefs

**Pull request merged**
