### PR TITLE
DO NOT MERGE: update synonym for MONDO_0011906

### PR DESCRIPTION
**Pull request by nicolevasilevsky**
I am getting these weird diffs, and looks like some other synonyms are being unintentionally deleted.

I am pushing this so I can show it to @matentzn

### CODE REVIEW

**Comment by cmungall** [comment]
Do not worry about the diffs here. I fixed casing by directly editing the obo file (eg Thyroid->thyroid). This resulted in redundancy. I did not normalize after, bad chris. It's natural that the next edit will eliminate duplicate lines.

**Comment by cmungall** [comment]
I am going to treat this as a normalization PR and go ahead and merge. If you made unintentional changes we can fix later

**Comment by nicolevasilevsky** [comment]
ok, sounds good, thanks @cmungall!

**Comment by cmungall** [comment]
You can now git pull on master and make new branches for your edits

**Pull request merged**
