### PR TITLE
New term: post-treatment Lyme disease syndrome

### LINKED ISSUE #8047: Post-treatment Lyme disease syndrome
### Label

post-treatment Lyme disease syndrome

### Synonyms

post-Lyme disease syndrome, PLDS

### Synonym type

exact

### Definition

The condition where patients experience prolonged symptoms due to Lyme disease is called Post-Treatment Lyme Disease Syndrome (PTLDS) and its cause is currently unknown. Although PTLDS is generally more common in women and in persons who have a difficult early disease course, the underlying causes are not well understood, and biomarkers to identify patients at risk for such outcomes are lacking. Thus, treatment strategies are symptom-based and often ineffective, leaving patients and physicians in a quandary about how to restore health.
https://www.cdc.gov/lyme/signs-symptoms/chronic-symptoms-and-lyme-disease.html
 https://wwwnc.cdc.gov/eid/article/29/6/22-1685_article
https://evsexplore.semantics.cancer.gov/evsexplore/concept/ncit/C119039
https://www.thelancet.com/journals/ebiom/article/PIIS2352-3964(23)00089-0/fulltext
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4847307/
See also:
https://www.hopkinslyme.org/lyme-disease/treatment-and-prognosis-of-lyme-disease/
https://www.hopkinsmedicine.org/news/newsroom/news-releases/2018/02/study-shows-evidence-of-severe-and-lingering-symptoms-in-some-after-treatment-for-lyme-disease
https://www.nih.gov/news-events/news-releases/nih-awards-will-fund-post-treatment-lyme-disease-syndrome-research
https://restorativehealthsolutions.com/lyme-disease/cdc-acknowledges-chronic-lyme-disease/

### Parent term

Lyme disease

### Children term(s)

_No response_

### ORCID Identifier

0000-001-9310-0163

### Website URL

https://www.cdc.gov/lyme/signs-symptoms/chronic-symptoms-and-lyme-disease.html

### Additional comments

We had an inquiry from a patient and from a support group.

### PR DESCRIPTION
**Pull request by sabrinatoro**
Closes #8047

### CODE REVIEW

**Review by twhetzel — COMMENTED** [review]
What is the parent of this new term? And should it have an inferred classification under MONDO:0021670 'post-infectious syndrome'?

**Comment by sabrinatoro** [comment]
The parent is inferred. It is the same as the term 'post-COVID-19 disorder' MONDO:0100320

**Comment by twhetzel** [comment]
The parent of 'post-COVID-19 disorder' MONDO:0100320 is MONDO:0021674 'post-viral disorder', is that the intended parent term? I thought Lyme disease was caused by a bacteria.

I still don't see the new term with a parent term when inferred.
Screenshot 2024-09-18 at 4 54 04 PM

**Comment by sabrinatoro** [comment]
@twhetzel 
The pattern used for this term is the "post-infectious-disease" pattern. 
This pattern was used for 'post-COVID-19 disorder' MONDO:0100320 which was autoclassified with the reasoner to MONDO:0021674 'post-viral disorder'.

Similarly, by using this pattern, 'post-treatment Lyme disease syndrome' is autoclassified (after the reasoner has run) as a 'post-bacterial disorder', as shown below. (
Screenshot 2024-09-19 at 7 45 09 AM
The reasoner has to run in order to see this inferred parent)

**Comment by twhetzel** [comment]
Yes, I understand the reasoner has to run to see the parent and the screenshot I posted was after running the reasoner. I checked again and after stopping and re-running the reasoner the inferred parent now shows up.

**Review by twhetzel — APPROVED** [review]
lgtm

**Pull request merged**
