### PR TITLE
Add ncbigene pipeline with new source

### PR DESCRIPTION
**Pull request by matentzn**
- [ ] Needs 24GB + memory
- [ ] @sabrinatoro to test

### CODE REVIEW

**Comment by sabrinatoro** [comment]
Note: I do not have enough memory to run the import refresh. I tried with 16, 20, 25, and 30 GB

**Comment by twhetzel** [comment]
@sabrinatoro  Are these the steps you are following: https://mondo.readthedocs.io/en/stable/editors-guide/import-terms-for-logical-axioms/#import-terms-into-mondo-for-use-in-logical-axioms

Let me know if you want me to try since I have more memory available on this laptop.

**Comment by matentzn** [comment]
@sabrinatoro I agree with @twhetzel thats probably for the best for now. I think I can reduce the memory foot print, I have reached out for some help.

In the meantime, I have updated the import so this PR is ready to go.

**Comment by matentzn** [comment]
@sabrinatoro If you like you can try it again, I reduce the memory footprint a bit and it should work with`MEMORY_GB=24`. But you can also just merge it, let Trish do import refresh in the meantime via SOP and punt making this less memory intensive moving forward.

**Comment by sabrinatoro** [comment]
@twhetzel could you please try running the import, and confirm that it works (ie that we have the non-human genes in Mondo; the list is in the manual_seed.txt which was updated in the PR).
If it works, then merge this PR.

**Comment by twhetzel** [comment]
@matentzn I refreshed the imports following this [Mondo Docs](https://mondo.readthedocs.io/en/stable/editors-guide/import-terms-for-logical-axioms/#import-terms-into-mondo-for-use-in-logical-axioms) using this `ncbigene-import-full` feature branch. 

This is the summary of changes:
src/ontology/imports/go_terms.txt        |   2 +
src/ontology/imports/hp_terms.txt        |   1 +
src/ontology/imports/merged_import.owl   | 308 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-
src/ontology/imports/ncbitaxon_terms.txt |  14 +++++

I wasn't expecting additional changes since you ran and committed these files. Is this^^ expected?

**Comment by twhetzel** [comment]
@matentzn sure, I just pushed those changed files to this PR.

**Comment by matentzn** [comment]
@twhetzel thanmk you, the changes are all expected! Awesome. Ready to merge!

**Review by twhetzel — APPROVED** [review]

**Pull request merged**
