### PR TITLE
add term MONDO:0033885 mitochondrial complex IV deficiency, nuclear-type

### LINKED ISSUE #2266: New OMIMPS: mitochondrial complex iv deficiency, nuclear-type
```
[Term]
id: MONDO:0033885
name: mitochondrial complex iv deficiency, nuclear-type
xref: OMIMPS:220110 {source="MONDO:equivalentTo"} ! mitochondrial complex iv deficiency, nuclear-type
```

### PR DESCRIPTION
**Pull request by nicolevasilevsky**
closes #2266

### CODE REVIEW

**Review by matentzn — APPROVED** [review]
Looks good but you will have to teach me how to do a review. Don't really know what I am looking for...

**Comment by nicolevasilevsky** [comment]
Should I manually add the children terms for this PS or will they get automatically classified?

**Comment by nicolevasilevsky** [comment]
https://omim.org/phenotypicSeries/PS220110

**Comment by nicolevasilevsky** [comment]
Some of the OMIM terms are already in Mondo, but it looks like not all of them are, for example, this is not in Mondo:
OMIM:619054

**Comment by matentzn** [comment]
I think the ones that don’t show up in the next slurp automatically! Keep
note of one, and double check whether that’s true! Don’t add any for now!

**Comment by nicolevasilevsky** [comment]
ok!

**Comment by nicolevasilevsky** [comment]
@matentzn this can be merged, yes?

**Comment by nicolevasilevsky** [comment]
Will you do another OMIM slurp before the next release?

**Comment by matentzn** [comment]
I will always keep slurping! :) you can merge I think.

**Pull request merged**
