### PR TITLE
Move Uberon to base

### LINKED ISSUE #542: corneal disease
update: to do: ask again in Slack after the holidays. _updated 12/22/21_

---
update: the Uberon dependency was fixed, but now it is dependent on the Uberon release. Note to self to check back on this in the future.

There was an Uberon release in mid-November but this was not fixed. I sent this message in Slack:
per Uberon ticket [#1779](https://github.com/obophenotype/uberon/issues/1779), I removed the superclass assertion of surface structure from cornea in Uberon (which is needed for Mondo # 542. However, I still see this superclass assertion in uberon.owl. and in the uberon-edit.obo file, this superclass is still there, coming from the NBO and PATO imports. Not sure how this should be addressed, any help is appreciated, thanks!

_Updated 2021-11-16 NV_

----

corneal disease is mistakenly listed as a child of integumentary system disease

### PR DESCRIPTION
**Pull request by matentzn**
fixes #542

To do:

```
sh run.sh make imports/uberon_import.owl
```

- Open mondo-edit.obo in protege
- find dangling classes
- add dangling classes to imports/*_terms.txt (where * is the ontology to import from)

Note:
- PR Removes all APs from uberon import aside from label, because the size exceeds the maximum permissible on GitHub actions.

### CODE REVIEW

**Comment by nicolevasilevsky** [comment]
@matentzn I don't see any dangling classes, is that what you would expect?
image

**Comment by matentzn** [comment]
If you can confirm the cornea issue sorted I am happy..

**Comment by nicolevasilevsky** [comment]
No :(

image

**Comment by nicolevasilevsky** [comment]
image

**Comment by nicolevasilevsky** [comment]
it still says this assertion is coming from Uberon :(

**Comment by matentzn** [comment]
I will look at this tomorrow, but this suggests the issue is not fixed in Uberon. Leave it to me.

**Comment by nicolevasilevsky** [comment]
You are the **_best_**, @matentzn, thanks!

**Comment by matentzn** [comment]
Ok, fixing this was easy. There is one flaw in the Mondo pipeline.

When we refresh imports, whenever we refresh imports, we _must_ use `-B` at the end of the make command. Please add that to all sections of the documentation. Otherwise, the mirror is never updated (see discussion in the obo slack #odk channel).

**Comment by matentzn** [comment]
Please check it again!

**Comment by matentzn** [comment]
Sorry, problems with QC.. looking into it.

**Comment by matentzn** [comment]
All good now but note that we were scraping the size limit for github actions, so I removed all APs from the Uberon classes aside from the rdfs:label for now. If you ever need more, then just ping me and we add them one by one! For now, just open mondo once more and check our actual problem is solved.

**Comment by nicolevasilevsky** [comment]
It works!!! 🎉 🎉 🎉 

Can I merge this?

**Review by nicolevasilevsky — APPROVED** [review]

**Pull request merged**
