### PR TITLE
mappings with only relevant columns

### PR DESCRIPTION
**Pull request by hrshdhgd**
New PR addressing https://github.com/mapping-commons/sssom-py/issues/214

### CODE REVIEW

**Comment by hrshdhgd** [comment]
Hey @nicolevasilevsky! I meant to request a review from Nico. I think it automatically tagged you since you're the owner.

**Comment by nicolevasilevsky** [comment]
Thanks for letting me know! Yeah, it automatically tags me and we don't know how to turn it off

**Review by matentzn — APPROVED** [review]

**Comment by matentzn** [comment]
Thank you @hrshdhgd

**Comment by hrshdhgd** [comment]
> Thanks for letting me know! Yeah, it automatically tags me and we don't know how to turn it off

Hey @nicolevasilevsky , I think [here's](https://docs.github.com/en/organizations/organizing-members-into-teams/managing-code-review-settings-for-your-team#disabling-auto-assignment) how you do it. Hopefully this works!

**Comment by nicolevasilevsky** [comment]
Cool - thanks for sharing that @hrshdhgd! :)

**Pull request merged**
