### PR TITLE
revise superclass assertions for down syndrome. Addresses #824

### PR DESCRIPTION
**Pull request by nicolevasilevsky**

### CODE REVIEW

**Comment by ShahimEssaid** [comment]
There was ID duplication on another branch and that error made it to other
places. It was clearly a mistake of not incrementing the ID for this class,
and it cased it to merge with MONDO:0100080.  This error was merged into
master recently and it was causing it to fail. Same for a couple of other
branches. Discussed with Nicole and she agreed that the ID was incorrect.
There, and the next used ID was MONDO:0100082, so MONDO:0100081 was missing
and MONDO:0100080 was applied to two classes. Fixing this was part of
getting the build to pass for master and a couple of other branches.

**Comment by ShahimEssaid** [comment]
See https://github.com/monarch-initiative/mondo/pull/838

**Comment by cmungall** [comment]
unfortunately the release has a messed up link as the ID was corrected in
the main stanza but not a link so we have

[Term]

id: MONDO:0013600

name: insomnia (disease)

...

is_a: MONDO:0100080 {source="
https://github.com/monarch-initiative/mondo/issues/531"} ! cardioectodermal
syndrome


let me know if something similar happens again, I am expert at fixing obo
files.

Also, never reuse - better to obsolete any ID that has been tainted in any
way!

**Comment by nicolevasilevsky** [comment]
Ok, we'll ask for your expert help if a similar issue arises, and will obsolete tainted IDs next time. Thanks for your help!

**Comment by cmungall** [comment]
conflicts.. and we have the weird ID shift again

**Comment by matentzn** [comment]
conflicts resolved.

**Pull request merged**
