### PR TITLE
add ORDO xref to cornea plana

### LINKED ISSUE #7573: Congenital cornea plana
Hi!  This term was obsoleted in the MONDO list sent to NORD.  MONDO list cornea plana with the subtypes 1 and 2. I think that congenital cornea plana should be listed as a synonym for cornea plana (or the name changed to congenital cornea plana as per Orphanet).

Thank you!
Best, Gioconda Alyea

### PR DESCRIPTION
**Pull request by nicolevasilevsky**
this is a bit of an unusual case:
- we obsoleted congenital corena plana but Gioconda asked that it be added back as an xref for cornea plana, so I added the ORDO xref and pointed to this term on the obsoleted term 
- close #7573

### CODE REVIEW

**Review by sabrinatoro — COMMENTED** [review]
@nicolevasilevsky could you please add the definition from Orphanet? https://www.orpha.net/en/disease/detail/53691?name=53691&mode=orpha
Thank you

**Comment by nicolevasilevsky** [comment]
done

at some point we'll sync all of these definitions, right? so we won't have to add them manually?

**Comment by twhetzel** [comment]
I think there are still general discussions to sync definitions. Is the work in this ticket a good use case/example of this issue?

**Comment by nicolevasilevsky** [comment]
yes - this is a case where there was no definition and I added the ORDO def

If you would like examples of where I update the definition that comes from ORDO, I can make a note next time I come across one

**Review by sabrinatoro — APPROVED** [review]
Looks good.

**Pull request merged**
