### PR TITLE
Ready to merge: Issue 528 - removed superclass from MONDO_0006044 nephrosclerosis

### PR DESCRIPTION
**Pull request by nicolevasilevsky**
removed superclass from MONDO_0006044 nephrosclerosis

addresses #528

### CODE REVIEW

**Comment by cmungall** [comment]
Remember that rather than removing a subClassOf that comes from a trusted source like ordo we usually turn it into an excluded_subClassOf annotation (may be worth pinging ORDO here - this is for Central diabetes insipidus isa Pituitary deficiency)

**Comment by nicolevasilevsky** [comment]
thanks for the reminder re: excluded subClassOf. Looks like it has been added now. Can this be merged?

**Comment by nicolevasilevsky** [comment]
Oh wait, maybe it hasn't, I will add now

**Comment by nicolevasilevsky** [comment]
ok, this should be ready to merge now @cmungall

**Comment by nicolevasilevsky** [comment]
Oh, I see you already merged, thanks! :)

**Pull request merged**
