### PR TITLE
DO NOT MERGE: check to ensure no omim subsumptions

### PR DESCRIPTION
**Pull request by cmungall**
See #962

### CODE REVIEW

**Comment by cmungall** [comment]
I expected this to fail, as it introduces a check for which we have known violations

**Comment by ShahimEssaid** [comment]
Still working on fixing this. A Jenkins update changed the "crumb" needed for the curl requests to be accepted. This has been happening since 10/29.

**Comment by cmungall** [comment]
Thanks!

Note this ticket will probably take a while to get merged so general fixed to the pipeline should go in a branch off master...

@nicolevasilevsky - can you work on this now? Check out this branch and try and get it to work. The goal is to investigate the omim-subsumption violations report. You can see this in the jenkins, but it's not very readable there. It may be better for you to run `make test` (in odk docker) locally and look at the csv that is made in excel or whatever you like.

**Comment by ShahimEssaid** [comment]
The real fix was in the Travis configuration on the Travis site. I'll apply
the one line I added to the .travis file to master but things work for now
without it anyway.

**Comment by nicolevasilevsky** [comment]
@cmungall @ShahimEssaid helped me generate the report, and I created a google doc [here](https://docs.google.com/spreadsheets/d/1oc4Za9A-zMldh4QYIDYtNc4_4SmyCRmp2zdK0GHlwZ4/edit#gid=1011052139).

Can you help explain the action item here?

There are over 1,000 terms that xref an OMIM class that are subclasses of a Mondo term that also xref a OMIM class. Do I need to review all of these individual classifications or is there something else that is meant to be done?

Thanks!

**Comment by nicolevasilevsky** [comment]
@cmungall is this something that still needs to be done?

**Comment by cmungall** [comment]
Do we not have a separate test for this now?

**Comment by nicolevasilevsky** [comment]
Yeah, I feel like there is a check for this. 
@matentzn could you confirm?
Thanks! :)

**Comment by matentzn** [comment]
This is the board of QC:
https://github.com/monarch-initiative/mondo/projects/10

I am checking it once per week and do one ticket of the top, so you can, if you want, sort the "NEXT" column as you see fit, and add from the backlog.. I have moved the OMIM sub OMIM ticket up top, but I wont get to it before end of the week, early next week.

**Comment by nicolevasilevsky** [comment]
Sounds good, thanks @matentzn. Are you going to work off this PR, or can this PR be closed? Thanks!

**Comment by matentzn** [comment]
I will deal with this elsewhere.

**Pull request closed without merging**
