### PR TITLE
Add clingen linkouts to Mondo, one off

### PR DESCRIPTION
**Pull request by matentzn**
This adds all ClinGen linkouts to Mondo as an experimental feature using a Mondo internal relationship.

Looks good in Protege:

image

### CODE REVIEW

**Comment by matentzn** [comment]
Note to reviewer:the 6 "removed lines" are the consequences of normalisation:

image

**Comment by twhetzel** [comment]
@matentzn is this intended for the August release?

**Comment by matentzn** [comment]
No need to merge this, I can update this PR again right after the release and we have it for the next one. Up to you. The PR does not affect anything in Mondo (only adds some new relations) so I would personally wave it through, but I see the value to sticking to process.

**Review by sabrinatoro — APPROVED** [review]
This is fantastic! Thank you @matentzn. 

I am ok with merging today, though it is not crucial. 
@twhetzel, I am letting you decide how you want to proceed (I can deal with conflict if we want to go ahead and merge for August release). 
If we don't merge today, this update will be part of the update of the ClinGen update, which is Week 3 of the release cycle (is that correct, @matentzn ?), and available in the September release.

**Review by twhetzel — APPROVED** [review]

**Pull request merged**
