### PR TITLE
revise logical def of 'cystic fibrosis associated meconium ileum'. 

### PR DESCRIPTION
**Pull request by nicolevasilevsky**
Addresses #685

Change logical def to:

'disease has location' some intestine

per https://github.com/EBISPOT/efo/issues/553

@cmungall I reviewed the diffs with @matentzn yesterday and he said there were not unintended changes happening - see #871

### CODE REVIEW

**Comment by cmungall** [comment]
Massive diff

**Comment by nicolevasilevsky** [comment]
Nico reviewed the diff with me and said there are three things in the diff:

1. serialization order of the xrefs changed
2. one obsolete term was located in the wrong part of the file
3. the label was changed in the text editor and not in Protege, and the OWL API changed the relationship annotations to the new label
and that nothing in the file has actually changed unintentionally

I don't know if there is a way to fix this?

**Comment by cmungall** [comment]
The solution is to use the same version of the owlapi. With the same
version of the api the ordering will be deterministic. If not this is a bug
we must report to the owlapi.

If it happens that we end up with a non-canonical serialization on master
then we need to fix it. Make a new PR that has no content changes, is just
a re-serialization, e.g. using robot. Mark it as such. Merge. Then make new
content PRs from that. Or rebase existing PRs if you don't want to redo
work.

**Comment by cmungall** [comment]
for this particular PR, either close and redo once master normalized, or normalize master then rebase here

**Comment by nicolevasilevsky** [comment]
I don't know how to do this, but I asked @matentzn for help.

**Comment by matentzn** [comment]
Alright, its done:

@cmungall Please review and merge our Protege 5.5. normalisation PR https://github.com/monarch-initiative/mondo/pull/896

I have already rebased this PR here against the above PR; so once the above one is merged, the diff between master and this (the cystic fibrosis) PR is only:

```
@@ -92989,7 +92989,7 @@ name: cystic fibrosis associated meconium ileum
 def: "Cystic fibrosis associated meconium ileum is a thickening and congestion of the meconium in the ileum in newborns, often the first sign of cystic fibrosis. In cystic fibrosis, the meconium can form a bituminous black-green mechanical obstruction in a segment of the ileum. Beyond this there may be a few separate grey-white globular pellets. Below this level, the bowel is a narrow and empty micro-colon. Above the level of the obstruction, there are several loops of hypertrophied bowel distended with fluid. No meconium is passed, and abdominal distension and vomiting appear soon after birth. About 20% of cases of cystic fibrosis present with meconium ileus, while approximately 20% of one series of cases of meconium ileus did not have cystic fibrosis The presence of meconium ileus is not related to the severity of the cystic fibrosis." [EFO:0004608]
 xref: EFO:0004608 {source="MONDO:equivalentTo"}
 is_a: MONDO:0005020 {source="https://github.com/EBISPOT/efo/issues/553"} ! intestinal disease
-relationship: disease_has_location UBERON:0000160 {source="EFO:0000784"} ! intestine
+relationship: disease_has_location UBERON:0001007 {source="EFO:0000784"} ! digestive system
 relationship: excluded_subClassOf MONDO:0009061 {source="EFO:0004608"} ! cystic fibrosis
```

**Comment by cmungall** [comment]
still a big diff?

**Pull request merged**
