### PR TITLE
add new OMIM terms

### LINKED ISSUE #2331: OMIM update 18. Nov. 2020
```
xref:  {source="MONDO:equivalentTo"} ! 

[Term]
id: MONDO:0026777
name: vexas syndrome
synonym: "VEXAS SYNDROME; VEXAS" RELATED  [OMIM:301054]
is_a: MONDO:0003847
xref: OMIM:301054 {source="MONDO:equivalentTo"} ! vexas syndrome

[Term]
id: MONDO:0033635
name: mitochondrial complex 4 deficiency, nuclear type 3
synonym: "MITOCHONDRIAL COMPLEX IV DEFICIENCY, NUCLEAR TYPE 3; MC4DN3" RELATED  [OMIM:619046]
is_a: MONDO:0003847
is_a: MONDO:0033885 {source="OMIM:619046"} ! mitochondrial complex IV deficiency, nuclear-type
xref: OMIM:619046 {source="MONDO:equivalentTo"} ! mitochondrial complex 4 deficiency, nuclear type 3

[Term]
id: MONDO:0033636
name: mitochondrial complex 4 deficiency, nuclear type 4
synonym: "MITOCHONDRIAL COMPLEX IV DEFICIENCY, NUCLEAR TYPE 4; MC4DN4" RELATED  [OMIM:619048]
is_a: MONDO:0003847
is_a: MONDO:0033885 {source="OMIM:619048"} ! mitochondrial complex IV deficiency, nuclear-type
xref: OMIM:619048 {source="MONDO:equivalentTo"} ! mitochondrial complex 4 deficiency, nuclear type 4

[Term]
id: MONDO:0033637
name: mitochondrial complex 4 deficiency, nuclear type 7
synonym: "MITOCHONDRIAL COMPLEX IV DEFICIENCY, NUCLEAR TYPE 7; MC4DN7" RELATED  [OMIM:619051]
is_a: MONDO:0003847
is_a: MONDO:0033885 {source="OMIM:619051"} ! mitochondrial complex IV deficiency, nuclear-type
xref: OMIM:619051 {source="MONDO:equivalentTo"} ! mitochondrial complex 4 deficiency, nuclear type 7

[Term]
id: MONDO:0033638
name: mitochondrial complex 4 deficiency, nuclear type 8
synonym: "MITOCHONDRIAL COMPLEX IV DEFICIENCY, NUCLEAR TYPE 8; MC4DN8" RELATED  [OMIM:619052]
is_a: MONDO:0003847
is_a: MONDO:0033885 {source="OMIM:619052"} ! mitochondrial complex IV deficiency, nuclear-type
xref: OMIM:619052 {source="MONDO:equivalentTo"} ! mitochondrial complex 4 deficiency, nuclear type 8

[Term]
id: MONDO:0033639
name: mitochondrial complex 4 deficiency, nuclear type 10
synonym: "MITOCHONDRIAL COMPLEX IV DEFICIENCY, NUCLEAR TYPE 10; MC4DN10" RELATED  [OMIM:619053]
is_a: MONDO:0003847
is_a: MONDO:0033885 {source="OMIM:619053"} ! mitochondrial complex IV deficiency, nuclear-type
xref: OMIM:619053 {source="MONDO:equivalentTo"} ! mitochondrial complex 4 deficiency, nuclear type 10

[Term]
id: MONDO:0033645
name: mitochondrial complex 4 deficiency, nuclear type 11
synonym: "MITOCHONDRIAL COMPLEX IV DEFICIENCY, NUCLEAR TYPE 11; MC4DN11" RELATED  [OMIM:619054]
is_a: MONDO:0003847
is_a: MONDO:0033885 {source="OMIM:619054"} ! mitochondrial complex IV deficiency, nuclear-type
xref: OMIM:619054 {source="MONDO:equivalentTo"} ! mitochondrial complex 4 deficiency, nuclear type 11

[Term]
id: MONDO:0033646
name: mitochondrial complex 4 deficiency, nuclear type 12
synonym: "MITOCHONDRIAL COMPLEX IV DEFICIENCY, NUCLEAR TYPE 12; MC4DN12" RELATED  [OMIM:619055]
is_a: MONDO:0003847
is_a: MONDO:0033885 {source="OMIM:619055"} ! mitochondrial complex IV deficiency, nuclear-type
xref: OMIM:619055 {source="MONDO:equivalentTo"} ! mitochondrial complex 4 deficiency, nuclear type 12

[Term]
id: MONDO:0033649
name: mitochondrial complex 4 deficiency, nuclear type 14
synonym: "MITOCHONDRIAL COMPLEX IV DEFICIENCY, NUCLEAR TYPE 14; MC4DN14" RELATED  [OMIM:619058]
is_a: MONDO:0003847
is_a: MONDO:0033885 {source="OMIM:619058"} ! mitochondrial complex IV deficiency, nuclear-type
xref: OMIM:619058 {source="MONDO:equivalentTo"} ! mitochondrial complex 4 deficiency, nuclear type 14

[Term]
id: MONDO:0033650
name: mitochondrial complex 4 deficiency, nuclear type 15
synonym: "MITOCHONDRIAL COMPLEX IV DEFICIENCY, NUCLEAR TYPE 15; MC4DN15" RELATED  [OMIM:619059]
is_a: MONDO:0003847
is_a: MONDO:0033885 {source="OMIM:619059"} ! mitochondrial complex IV deficiency, nuclear-type
xref: OMIM:619059 {source="MONDO:equivalentTo"} ! mitochondrial complex 4 deficiency, nuclear type 15

[Term]
id: MONDO:0033651
name: mitochondrial complex 4 deficiency, nuclear type 16
synonym: "MITOCHONDRIAL COMPLEX IV DEFICIENCY, NUCLEAR TYPE 16; MC4DN16" RELATED  [OMIM:619060]
is_a: MONDO:0003847
is_a: MONDO:0033885 {source="OMIM:619060"} ! mitochondrial complex IV deficiency, nuclear-type
xref: OMIM:619060 {source="MONDO:equivalentTo"} ! mitochondrial complex 4 deficiency, nuclear type 16

[Term]
id: MONDO:0033652
name: mitochondrial complex 4 deficiency, nuclear type 17
synonym: "MITOCHONDRIAL COMPLEX IV DEFICIENCY, NUCLEAR TYPE 17; MC4DN17" RELATED  [OMIM:619061]
is_a: MONDO:0003847
is_a: MONDO:0033885 {source="OMIM:619061"} ! mitochondrial complex IV deficiency, nuclear-type
xref: OMIM:619061 {source="MONDO:equivalentTo"} ! mitochondrial complex 4 deficiency, nuclear type 17

[Term]
id: MONDO:0033653
name: mitochondrial complex 4 deficiency, nuclear type 18
synonym: "MITOCHONDRIAL COMPLEX IV DEFICIENCY, NUCLEAR TYPE 18; MC4DN18" RELATED  [OMIM:619062]
is_a: MONDO:0003847
is_a: MONDO:0033885 {source="OMIM:619062"} ! mitochondrial complex IV deficiency, nuclear-type
xref: OMIM:619062 {source="MONDO:equivalentTo"} ! mitochondrial complex 4 deficiency, nuclear type 18

[Term]
id: MONDO:0033654
name: mitochondrial complex 4 deficiency, nuclear type 19
synonym: "MITOCHONDRIAL COMPLEX IV DEFICIENCY, NUCLEAR TYPE 19; MC4DN19" RELATED  [OMIM:619063]
is_a: MONDO:0003847
is_a: MONDO:0033885 {source="OMIM:619063"} ! mitochondrial complex IV deficiency, nuclear-type
xref: OMIM:619063 {source="MONDO:equivalentTo"} ! mitochondrial complex 4 deficiency, nuclear type 19

[Term]
id: MONDO:0033655
name: mitochondrial complex 4 deficiency, nuclear type 20
synonym: "MITOCHONDRIAL COMPLEX IV DEFICIENCY, NUCLEAR TYPE 20; MC4DN20" RELATED  [OMIM:619064]
is_a: MONDO:0003847
is_a: MONDO:0033885 {source="OMIM:619064"} ! mitochondrial complex IV deficiency, nuclear-type
xref: OMIM:619064 {source="MONDO:equivalentTo"} ! mitochondrial complex 4 deficiency, nuclear type 20

[Term]
id: MONDO:0033656
name: mitochondrial complex 4 deficiency, nuclear type 21
synonym: "MITOCHONDRIAL COMPLEX IV DEFICIENCY, NUCLEAR TYPE 21; MC4DN21" RELATED  [OMIM:619065]
is_a: MONDO:0003847
is_a: MONDO:0033885 {source="OMIM:619065"} ! mitochondrial complex IV deficiency, nuclear-type
xref: OMIM:619065 {source="MONDO:equivalentTo"} ! mitochondrial complex 4 deficiency, nuclear type 21

[Term]
id: MONDO:0033657
name: leukodystrophy, hypomyelinating, 20
synonym: "LEUKODYSTROPHY, HYPOMYELINATING, 20; HLD20" RELATED  [OMIM:619071]
is_a: MONDO:0003847
is_a: MONDO:0019046 {source="OMIM:619071"} ! leukodystrophy
xref: OMIM:619071 {source="MONDO:equivalentTo"} ! leukodystrophy, hypomyelinating, 20

[Term]
id: MONDO:0033658
name: neurodevelopmental disorder with seizures and brain atrophy
synonym: "NEURODEVELOPMENTAL DISORDER WITH SEIZURES AND BRAIN ATROPHY; NEDSEBA" RELATED  [OMIM:619072]
is_a: MONDO:0003847
xref: OMIM:619072 {source="MONDO:equivalentTo"} ! neurodevelopmental disorder with seizures and brain atrophy

[Term]
id: MONDO:0033662
name: neurodevelopmental disorder with microcephaly, seizures, and brain atrophy
synonym: "NEURODEVELOPMENTAL DISORDER WITH MICROCEPHALY, SEIZURES, AND BRAIN ATROPHY; NEDMISB" RELATED  [OMIM:619076]
is_a: MONDO:0003847
xref: OMIM:619076 {source="MONDO:equivalentTo"} ! neurodevelopmental disorder with microcephaly, seizures, and brain atrophy

[Term]
id: MONDO:0033664
name: kilquist syndrome
synonym: "KILQUIST SYNDROME; KILQS" RELATED  [OMIM:619080]
is_a: MONDO:0003847
xref: OMIM:619080 {source="MONDO:equivalentTo"} ! kilquist syndrome

[Term]
id: MONDO:0033665
name: deafness, autosomal dominant 78
synonym: "DEAFNESS, AUTOSOMAL DOMINANT 78; DFNA78" RELATED  [OMIM:619081]
is_a: MONDO:0003847
is_a: MONDO:0019587 {source="OMIM:619081"} ! autosomal dominant nonsyndromic deafness
xref: OMIM:619081 {source="MONDO:equivalentTo"} ! deafness, autosomal dominant 78

[Term]
id: MONDO:0033667
name: delpire-mcneill syndrome
synonym: "DELPIRE-MCNEILL SYNDROME; DELMNES" RELATED  [OMIM:619083]
is_a: MONDO:0003847
xref: OMIM:619083 {source="MONDO:equivalentTo"} ! delpire-mcneill syndrome

[Term]
id: MONDO:0033668
name: deafness, autosomal dominant 79
synonym: "DEAFNESS, AUTOSOMAL DOMINANT 79; DFNA79" RELATED  [OMIM:619086]
is_a: MONDO:0003847
is_a: MONDO:0019587 {source="OMIM:619086"} ! autosomal dominant nonsyndromic deafness
xref: OMIM:619086 {source="MONDO:equivalentTo"} ! deafness, autosomal dominant 79

[Term]
id: MONDO:0033669
name: noonan syndrome 13
synonym: "NOONAN SYNDROME 13; NS13" RELATED  [OMIM:619087]
is_a: MONDO:0003847
is_a: MONDO:0018997 {source="OMIM:619087"} ! Noonan syndrome
xref: OMIM:619087 {source="MONDO:equivalentTo"} ! noonan syndrome 13

[Term]
id: MONDO:0033670
name: deafness, autosomal recessive 116
synonym: "DEAFNESS, AUTOSOMAL RECESSIVE 116; DFNB116" RELATED  [OMIM:619093]
is_a: MONDO:0003847
is_a: MONDO:0019588 {source="OMIM:619093"} ! autosomal recessive nonsyndromic deafness
xref: OMIM:619093 {source="MONDO:equivalentTo"} ! deafness, autosomal recessive 116

[Term]
id: MONDO:0033671
name: spermatogenic failure 45
synonym: "SPERMATOGENIC FAILURE 45; SPGF45" RELATED  [OMIM:619094]
is_a: MONDO:0003847
is_a: MONDO:0004983 {source="OMIM:619094"} ! azoospermia
xref: OMIM:619094 {source="MONDO:equivalentTo"} ! spermatogenic failure 45

[Term]
id: MONDO:0033673
name: spermatogenic failure 46
synonym: "SPERMATOGENIC FAILURE 46; SPGF46" RELATED  [OMIM:619095]
is_a: MONDO:0003847
is_a: MONDO:0004983 {source="OMIM:619095"} ! azoospermia
xref: OMIM:619095 {source="MONDO:equivalentTo"} ! spermatogenic failure 46

```

### PR DESCRIPTION
**Pull request by nicolevasilevsky**
closes #2331

### CODE REVIEW

**Comment by nicolevasilevsky** [comment]
- [ ] add syn: vacuoles, E1 enzyme, X-linked, autoinflammatory, somatic syndrome to VEXAS
- [ ] add abbreviation tag

**Comment by matentzn** [comment]
Have fun reviewing this: https://github.com/monarch-initiative/mondo/pull/2336

There are about 3500K of these..

**Comment by cmungall** [comment]
Not sure what this is:
> add abbreviation tag, dependent on #2336

we already have the tag?

**Comment by cmungall** [comment]
Not all checkboxes are ticked - I recommend marking as draft if not ready for review

this looks great though I will merge now

> bring in corresponding genes for OMIM terms

still needs to be done in the slurp, and we still want to periodically re-sync, but this is global and not local to this PR

**Comment by matentzn** [comment]
I moved the remaining checkboxes in other tickets

**Pull request merged**
