### PR TITLE
add new term: alveolar capillary dysplasia without misalignment

### PR DESCRIPTION
**Pull request by nicolevasilevsky**
- revised label for MONDO_0009934 'alveolar capillary dysplasia with misalignment of pulmonary veins'

Open questions:
@mgriese 
- would it make sense to create a grouping class for these two terms, eg **alveolar capillary dysplasia**? Is this term a more general term that could group the with and without misalignment terms together?  https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C98809
- Could you help us with the text definition for the without misalignment term? We current have:
A rare form of interstitial and vascular lung disease that presents as severe pulmonary hypertension and refractory hypoxemia early in life.

Thank you!

cc @kallia-p

### CODE REVIEW

**Comment by nicolevasilevsky** [comment]
related to https://github.com/monarch-initiative/mondo/pull/3147

**Comment by kallia-p** [comment]
@nicolevasilevsky @mgriese In Pubmed I found only one study reporting ACD without misalignment of the pulmonary veins PMID:9514134.

**Comment by mgriese** [comment]
OK, we have several cases; is difficult to publish without genetics; would just list as a term (with the citation above)

**Comment by mgriese** [comment]
There may be more in pubmed after quick check: 33766794,

**Comment by mgriese** [comment]
Regarding the question above: as I am not a pathologist expert in this field,  I am not able to provide a good histopathologic definition. The definition you gave is fine.

**Comment by nicolevasilevsky** [comment]
too many conflicts, will redo

**Pull request closed without merging**
