### PR TITLE
Create kglc-workflow.md

### PR DESCRIPTION
**Pull request by nicolevasilevsky**

### CODE REVIEW

**Review by hrshdhgd — APPROVED** [review]

**Comment by hrshdhgd** [comment]
I made minor tweaks, hope that is ok.

**Comment by nicolevasilevsky** [comment]
of course, thanks!

**Comment by matentzn** [comment]
Remember this goes out to the Mondo user community. They don't care about KGCL neither what it is, nor anything else. They just care that you can magically add a synonym using a commend in a github issue.

I read through the instructions, I would have liked to

- avoid use of the word "KGCL" (both in the title and the filename)
- Use a concrete ID from a Mondo class adding a concrete synonym (one that already exists, does no matter)

If you feel though @nicolevasilevsky it is good as is, we can send it to the list, but it seems a bit too technical to me atm.

**Comment by nicolevasilevsky** [comment]
I didn't know this was meant to be user facing documentation. 

Do we want users to obsolete terms? I understand that this will be done on a PR, but we need to add terms to the obsoletion list and leave an issue open for 2 months before we obsolete a term, so I don't think this would be a good workflow for users to use (but we (curators) could use it.

I am going to test this out.

**Pull request merged**
