### PR TITLE
#716- revise classification of terms under 'disease or disorder'

### PR DESCRIPTION
**Pull request by nicolevasilevsky**
@cmungall I added a logical def to MONDO_0019542 acute liver failure and it is no longer inferred to be a subclass of 'disease or disorder'. Is this the proper way to address this ticket?

I will work on other classes too

Addresses #716

### CODE REVIEW

**Comment by nicolevasilevsky** [comment]
Looking at these more closely, I don't know if we can add logical defs to these terms, so should we manually assert new parents for these classes?

**Comment by nicolevasilevsky** [comment]
@cmungall there is not a mondo class for 'liver failure', so I cannot add the logical def 'liver failure' and 'has modifier' some 'acute'"

**Comment by nicolevasilevsky** [comment]
should I remove this logical def from acute liver failure?
'acute disease'
 and ('disease has location' some liver)

**Comment by cmungall** [comment]
'acute disease'
and ('disease has location' some liver)

This includes any acute disease in the liver, acute liver failure is more specific

there is an argument for making a triad here (acute, chronic, agnostic), but this should be checked if this is clinically meaningful

this suggests its not unreasonable:
https://en.wikipedia.org/wiki/Liver_failure

**Comment by nicolevasilevsky** [comment]
Closing this here - addressed this on PR https://github.com/monarch-initiative/mondo/pull/1871

**Pull request closed without merging**
