### PR TITLE
updated "familial prostate cancer" branch

### PR DESCRIPTION
**Pull request by sabrinatoro**
Addresses #8060
See issue for details

### CODE REVIEW

**Comment by sabrinatoro** [comment]
@matentzn and @twhetzel I don't know what the QC fail is and how to resolve it. Could you please help? Thank you!

**Comment by matentzn** [comment]
@sabrinatoro this was a temporary glitch - when this happens (i.e. whenever you dont know whats going on :P) just run the QC check again! You can do so by clicking on "Re-run all jobs"

image

**Comment by sabrinatoro** [comment]
> this was a temporary glitch - when this happens (i.e. whenever you dont know whats going on :P) just run the QC check again! You can do so by clicking on "Re-run all jobs"

I almost did run the QC checks again! Then I stop myself thinking that "it is just wishful thinking" :-) Thanks @matentzn

**Review by nicolevasilevsky — APPROVED** [review]
looks good @sabrinatoro

**Pull request merged**
