### PR TITLE
First draft ncbigene and fix hgnc import

### LINKED ISSUE #7327: Add NCBIGene to Mondo to refer to non-human animal genes
Part of #7271

Please add the NCBI Genes to Mondo so they are available for axioms annotations of non-human animal genetic diseases.

I assume adding these genes will require adding a new import (?). 

The list of required NCBIGenes can be found in [this spreadsheet](https://docs.google.com/spreadsheets/d/1aKuKc2yKy4Z1_yzntsOSi-Z-2V_AMKdmcwOZsVpUwtM/edit#gid=1157876657) 
@katiermullen can answer any questions.
Thanks!

### PR DESCRIPTION
**Pull request by matentzn**
This PR fixes #7327.

It includes

- a draft import for ncbigene based on what Monarch currently has, covering only cow/pig/dog/chicken (cc @kevinschaper)
- an update to the HGNC import, which used a stale, outdated source in monarch archive. using gene symbol as label now.
- some minor syntax bugs in SPARQL I stumbled across while working on this.

It is missing:

- [ ] Species beyond cow/pig/dog/chicken
- [ ] Proper testing (see if the contents of the refreshed imports still look good)

@twhetzel what do you think? Any concerns with the changes proposed?

### CODE REVIEW

**Comment by sabrinatoro** [comment]
@matentzn I have tested importing a dog gene into Mondo, and it did work.

**Review by sabrinatoro — APPROVED** [review]

**Comment by twhetzel** [comment]
@matentzn where/how is this missing species beyond cow/pig/dog/chicken?

**Review by twhetzel — APPROVED** [review]
generally seems ok

**Comment by matentzn** [comment]
> @matentzn was that limited by taxon because that is Monarch has? How is this missing species beyond cow/pig/dog/chicken, was the spreadsheet filtered to only include those taxon?

Exactly - in this PR we are using the limited subset that Monarch has, and we need to build a  general pipeline for the rest of the species.

**Pull request merged**
