### PR TITLE
ROBOT template based obsoletion

### LINKED ISSUE #3596: [Obsolete] 'systemic disease'
**Mondo term (ID and Label)**
'systemic disease'

**Reason for deprecation**
it is hard to classify underneath this term. There is a combination of rheumatic and germline disorders.
for example, diabetes is a systemic disorder, but is not classified as a child.

**Suggested term to consider**

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

### PR DESCRIPTION
**Pull request by matentzn**
close #3596 #3594 #3172 #324 #324 #324 #324 #324 #3573 #324 #3570 #324 #3575 #3570 #324 #3442

### CODE REVIEW

**Comment by matentzn** [comment]
There is a problem here with robot remove.. I can either tell it to fix the class hierarchy (i.e if A sub B sub C, you delete B, then add A sub C) or I can tell it not to do it (which means A becomes a floater and needs to be classified manually. The problem is, if I tell it to fix the class hierarchy, it will fix _all of it_. Which means it will try to fix a million subclass relations that we did not tell it to :( Shit

**Comment by nicolevasilevsky** [comment]
Oh dear.
It's not the end of the world if this workflow doesn't work out, I can always obsolete these classes one at a time.

**Comment by nicolevasilevsky** [comment]
to do:
check in protege
once passes, merge
after
create new PR with this command
sh run.sh make make related_to_exact_where_label

**Comment by nicolevasilevsky** [comment]
@matentzn 

These terms were missing owl:depracated true. I fixed it manually.

Some terms were left orphaned because the terms that were obsoleted were children of 'disease or disorder'. I added parents to those terms. This won't happen very often.

**Pull request merged**
