### PR TITLE
Replaces all ORDO: with Orphanet prefixes

### PR DESCRIPTION
**Pull request by matentzn**
@nicolevasilevsky this is massive, I would suggest you first merge everything else, and then this, because it conflicts with nearly all other possible PRs.. We can recreate this PR very simply running:

```
sed -i '' 's/ORDO:/Orphanet:/g' mondo-edit.obo
```

Any time you have the least amount of PRs open

### CODE REVIEW

**Comment by maglott** [comment]
When will this be released?  Not all of our code is ready for a switch from ORDO to Orphanet.

**Comment by matentzn** [comment]
Right now, there are both ORDO: and Orphanet: prefixes scattered throughout Mondo - we just seek to unify them both into `Orphanet`. If your code is not looking at `Orphanet` for axiom annotations that it is already missing things!

This will go life with the next release.. Please let me know if there is anything we can do to help you here.

**Comment by matentzn** [comment]
We are always interested to learn how you use which aspects of Mondo! :) Thanks for keeping us in the loop!

**Comment by nicolevasilevsky** [comment]
redoing on another PR

**Pull request closed without merging**
