### PR TITLE
obsolete ORDO grouping classes

### PR DESCRIPTION
**Pull request by nicolevasilevsky**

### CODE REVIEW

**Comment by sabrinatoro** [comment]
@nicolevasilevsky : Everything I checked looks good!

**Comment by nicolevasilevsky** [comment]
@sabrinatoro @matentzn 
I noticed one class has an excluded subclassOf annotation on it. We should remove these too. @matentzn could you update the pipeline to remove these?

@sabrinatoro could you do a SPARQL query for any obsolete class that has the annotation http://purl.obolibrary.org/obo/mondo#excluded_subClassOf?

I can remove them manually in this PR. I suspect there are not very many.

Thanks!

**Comment by nicolevasilevsky** [comment]
@matentzn 
Some of these still have definitions too. We should either remove the definitions or prepend them with OBSOLETE. I think we should remove the definitions.

**Comment by sabrinatoro** [comment]
@nicolevasilevsky 
Here is your query: 
https://api.triplydb.com/s/aVNkENJKn

**Comment by sabrinatoro** [comment]
@nicolevasilevsky Here is the query to find the obsolete terms that has "excluded subclass of" annotations:
https://api.triplydb.com/s/3HIFkqM-9

**Pull request merged**
