### PR TITLE
add new superclasses based on ICD10

### PR DESCRIPTION
**Pull request by nicolevasilevsky**
this PR adds new superclasses based on ICD10, see related PR: https://github.com/monarch-initiative/mondo/pull/7111

[ROBOT spreadsheet is here](https://docs.google.com/spreadsheets/d/1Fz9renG5Q2w5P3IRqB-r8Kd7CqHDa0e3C3vHDbD0VAM/edit#gid=23158831)

### CODE REVIEW

**Review by twhetzel — APPROVED** [review]
All new superclass assertions include a source. 

@nicolevasilevsky let me know if I should also verify your choice of the superclass or anything else in this PR.

**Comment by nicolevasilevsky** [comment]
Thanks @twhetzel. If you have time, it would be great if you could confirm you agree with adding these parents - it would probably be easiest to review the spreadsheet linked above.
Thank you!

**Review by twhetzel — COMMENTED** [review]
After looking over the ROBOT template and viewing Mondo hierarchies in Protege, I have some questions/comments for terms.

**Review by twhetzel — CHANGES_REQUESTED** [review]
After looking over the ROBOT template and viewing Mondo hierarchies in Protege, I have some questions/comments for terms.

**Review by twhetzel — APPROVED** [review]
I checked out the branch and reviewed the asserted hierarchy in Protege and the changes in the ROBOT template look good.

**Pull request merged**
