### PR TITLE
split Teebi hypertelorism syndrome

### LINKED ISSUE #4500: split term: MONDO:0007780 'hypertelorism, Teebi type'
**Term to split:**
MONDO:0007780 'hypertelorism, Teebi type'

**Name for new terms:** Note - when a term should be split, there should be 2+ new terms. Please list the new labels below. 
MONDO:800025 'hypertelorism, Teebi type'
MONDO:0030639 teebi hypertelorism syndrome

- [x] obsolete  MONDO:0007780 'hypertelorism, Teebi type'

- [x] add new OMIMPS:

[Term]
id: MONDO:0030639
name: Teebi hypertelorism syndrome
xref: OMIMPS:145420 {source="MONDO:equivalentTo"} ! Teebi hypertelorism syndrome
is_a: MONDO:0003847 {source="OMIMPS:145420"} ! l'Mendelian disease'
relationship: has_modifier MONDO:0021152 {source="OMIMPS:145420"} ! inherited

- [x] add new term:

[Term]
id: MONDO:800025
name: Teebi hypertelorism syndrome 1
def: "A rare genetic disease characterized by hypertelorism with facial features that can closely resemble craniofrontonasal dysplasia, such as prominent forehead, widow's peak, heavy and broad eyebrows, long palpebral fissures, ptosis, high and broad nasal bridge, short nose, low-set ears, natal teeth, thin upper lip and a grooved chin, as well as limb (i.e. fifth-finger clinodactyly, pes adductus, mild interdigital webbing), urogenital (i.e. bilateral cryptorchidism and shawl scrotum in males) and umbilical (i.e. hernia/small omphalocele) anomalies and cardiac (i.e. ventricular or atrial septal defect, patent ductus arteriosus) defects. Additional findings such as polycystic kidneys and iridochorioretinal colobomas have also been reported and psychomotor development is normal. The facial features can also resemble Aarskog and Opitz G/BBB syndromes." [Orphanet:1519, https://orcid.org/0000-0001-5208-3432]
subset: ordo_malformation_syndrome {source="Orphanet:1519"}
synonym: "Brachycephalofrontonasal dysplasia" EXACT [OMIM:145420, Orphanet:1519]
synonym: "craniofrontonasal dysplasia, Teebi type" EXACT [Orphanet:1519]
synonym: "hypertelorism, Teebi type" EXACT [OMIM:145420]
synonym: "Teebi hypertelorism syndrome" EXACT [Orphanet:1519]
synonym: "Teebi syndrome" EXACT [Orphanet:1519]
xref: GARD:0000957 {source="MONDO:equivalentTo", source="Orphanet-shared", source="OMIM-shared"}
xref: ICD10:Q87.0 {source="ORDO:1519/attributed", source="ORDO:1519/ntbt", source="Orphanet:1519"}
xref: OMIM:145420 {source="MONDO:equivalentTo", source="ORDO:1519/e", source="Orphanet:1519"}
xref: Orphanet:1519 {source="MONDO:equivalentTo", source="OMIM:145420"}
xref: SCTID:724284005 {source="MONDO:equivalentTo"}
xref: UMLS:C0796179 {source="MONDO:equivalentTo"}
xref: UMLS:C1840378 {source="NCBI:mim2gene_medline", source="OMIM:145420", source="MONDO:notFoundInDiseaseSubset", source="Orphanet:1519"}
xref: UMLS:CN199596 {source="MONDO:equivalentTo"}
is_a: MONDO:0030639 {source="OMIM:145420", source="indirect"} ! Teebi hypertelorism syndrome

- [x] add logical def that includes gene (see OMIM: https://omim.org/entry/145420)

Related to https://github.com/monarch-initiative/mondo/issues/4498

### PR DESCRIPTION
**Pull request by nicolevasilevsky**
close #4500

### CODE REVIEW

**Comment by nicolevasilevsky** [comment]
@matentzn @sabrinatoro I don't understand why this failed. I wonder if it doesn't like the new relation?

'Teebi hypertelorism syndrome'
 and ('has material basis in gain of function germline mutation in' some SPECC1L)

**Comment by sabrinatoro** [comment]
The relation should be :
has material basis in germline mutation in
(ie without the "gain of function")

Maybe it is because the other PR related to the acquired/inherited hasn't been merged yet?

**Comment by nicolevasilevsky** [comment]
we don't have that relation in Mondo at the moment.

**Comment by sabrinatoro** [comment]
@nicolevasilevsky 
This is coming with the PR https://github.com/monarch-initiative/mondo/pull/4800
(that PR is the gift that keeps on giving! :-D)

**Pull request closed without merging**
