### PR TITLE
Notebook to demo access to mondo using oak

### LINKED ISSUE #6805: Create a jupyter notebook for Mondo processing with OAK
Create a jupyter notebook (src/scripts/notebooks/mondo.ipynb with the following features:

- [x] A nice header (first cell) saying something like "code examples interacting with Mondo"
- [x] An explanation on how to install OAK (links to docs)
- [x] Code cell 1: An example of loading mondo (`:obo` selector) in python, not CLI (!)
- [x] Code cell 2: Traversing through all children of "tuberculosis" (look up ID on OLS) and extract the following features from each term:
    - [x] Cross-species analog relation (its an annotation property, not sure how it looks in OAK)
    - [x] conformsTo relation to pattern (blocked by #6806)
    - [x] A list of all children
    - [x] A list of all parents
    - [x] The label
    - [x] A list of all disease mappings
- [x] Code cell 3: print the results for a single term that exhibits all of the above (will need to search for one).

For all cells, add a few words explanatory text what we do here. Format nicely. This is for our Data Science users.

When done, assign to Sabrina to link from user docs (make a more comprehensive user doc for how users can use OAK with Mondo).

### PR DESCRIPTION
**Pull request by hrshdhgd**
Fixes #6805

### CODE REVIEW

**Comment by twhetzel** [comment]
@matentzn updates to the notebook are added

**Review by matentzn — COMMENTED** [review]
Awesome, this will be very useful moving forward, not just to the immediate use case.

1. Maybe add all dependencies of the notebook in one of the cells, including `pandas`, `curies` etc?
2. for the URI to curie conversion process, I think we ca use

```python
converter = adapter.converter
print(converter.compress("http://purl.obolibrary.org/obo/GO_0005634"))
```

Maybe it is possible to do load curies.get_obo_converter(), chain it with whatever converter is in adapter.converter and then use that object to do the curie-uri conversion

3. Limit the last output to the top 5 rows?

None of this is particularly important, feel free to merge at your own discretion! Very nice work!

**Comment by twhetzel** [comment]
@matentzn I changed this Draft PR to a live PR. Let me know if you're still ok for this to be merged.

**Comment by matentzn** [comment]
Absolutely, please merge any time. To fully close the issue, you could add a markdown file with "Examples how to use Mondo" to the docs, add a section called "Notebooks" and link your notebook. Then we have something solid for the future to iterate over. Thank you!

**Review by matentzn — APPROVED** [review]

**Pull request merged**
