### PR TITLE
add synonym to 'oculocutaneous albinism'. Addresses # 641

### PR DESCRIPTION
**Pull request by nicolevasilevsky**
@cmungall should I add dbxefs to these synonyms? If yes, what should I add? Should I add Donna Maglott's ORCID, since she requested the new synonyms or my ORCID since I added them? 
Thanks!

### CODE REVIEW

**Comment by nicolevasilevsky** [comment]
or I could xref the ticket #641 ?

**Comment by cmungall** [comment]
go ahead and use the ticket URL

**Comment by nicolevasilevsky** [comment]
@cmungall 
Donna made a request for the new term 'nonsyndromic oculocutaneous albinism', but Ada pointed out that this was really a synonym of 'oculocutaneous albinism', so I added it as a synonym.

Since the non-syndromic presentation is a synonym, it shouldn't be a child of syndromic syndrome, so I removed the equivalence axiom:
intersection_of: MONDO:0018910 ! oculocutaneous albinism
intersection_of: has_modifier MONDO:0021127 ! has a syndromic presentation

Does this make sense?

**Comment by cmungall** [comment]
Can we coordinate with @ORDO?

https://www.ebi.ac.uk/ols/ontologies/ordo/terms?iri=http%3A%2F%2Fwww.orpha.net%2FORDO%2FOrphanet_98706

https://www.ebi.ac.uk/ols/ontologies/ordo/terms?iri=http%3A%2F%2Fwww.orpha.net%2FORDO%2FOrphanet_98706

**Comment by nicolevasilevsky** [comment]
@cmungall what do I need to tell ordo? Just that we added a synonym to 'oculocutaneous albinism'?

I think this is otherwise ready to merge.

**Comment by cmungall** [comment]
OK, I still think it's better to be explicit have the label be nonsyndromic here as it sounds like syndrome-agnostic form but I'll go ahead and merge

**Pull request merged**
