### PR TITLE
refresh imports

### PR DESCRIPTION
**Pull request by twhetzel**
Followed the new (almost ready to be merged refresh import docs, https://github.com/monarch-initiative/mondo/pull/7492/files) to refresh the imports to add:
```
http://identifiers.org/hgnc/17985
http://purl.obolibrary.org/obo/NCBITaxon_3052342
http://purl.obolibrary.org/obo/NCBITaxon_3052343
```

### CODE REVIEW

**Review by sabrinatoro — APPROVED** [review]
@twhetzel 
I think you didn't do the following step:
 Open `mondo-edit.obo` in Protege and save the ontology (as .obo).
 
 I just did and now the QC are running.
I am approving this PR because the rest is as expected. We can merge it as soon as the QC passed.

**Comment by twhetzel** [comment]
@sabrinatoro I did that step, `Open mondo-edit.obo in Protege and save the ontology (as .obo).` and verified the gene I added was found in Protege.

**Comment by sabrinatoro** [comment]
@twhetzel 
weird... because when I did it, there were some changes in the mondo-edit.obo (as shown in the diff).
We should keep an eye on that!

**Comment by twhetzel** [comment]
@katiermullen I already created a PR to update the taxon subset file.

@sabrinatoro I think that step should just be part of the responsibility of whoever refreshes the import. Do you agree?

**Comment by sabrinatoro** [comment]
@twhetzel 
Are you talking about the step of adding the NCBITaxon to the obo file ?
I don't have a strong opinion on that (I never thought about it until now). 
But yes, we could make it that it is the responsibility of whoever refreshes the import.

**Pull request merged**
