### PR TITLE
New OMIM terms 2020.11.07

### PR DESCRIPTION
**Pull request by matentzn**
@nicolevasilevsky this is only a draft pull request for you two fix up (synonyms etc). This workflow is simpler than making intermediate tickets - I make a draft PR, you fix it (making the synonyms lower case, breaking out the abbreviations). You can then make it a proper PR when you are done. Sounds ok?

### CODE REVIEW

**Comment by matentzn** [comment]
Of course in your todo is also deciding whether a term is, indeed, a real disease - I am not doing that either :D Just double-check everything. I will check what you fix and see what we can automate.

**Comment by nicolevasilevsky** [comment]
Sounds great!

**Comment by nicolevasilevsky** [comment]
@matentzn I think this can be merged, yeah? Should I go ahead and merge these types of tickets going forward?

**Comment by matentzn** [comment]
If you are reasonably confident that the disease ended up in the right parts of the hierarchy, as well as not being duplicates of other diseases, you can merge it!

**Comment by nicolevasilevsky** [comment]
I made one edit to the hierarchy, everything else looks fine.

Before I merge- should I manually axiomatize the classes that are part of the phenotypic series like 

[Term]  
id: MONDO:0033615  
name: coenzyme q10 deficiency, primary, 9  
synonym: "COQ10D9" EXACT [OMIM:619028]  
xref: OMIM:619028 {source="MONDO:equivalentTo"}  
is_a: MONDO:0003847 ! Mendelian disease  
is_a: MONDO:0018151 {source="OMIM:619028"} ! coenzyme Q10 deficiency  

It should have the equiv axiom:

'coenzyme Q10 deficiency' and ('disease has basis in dysfunction of' some COQ5)

Or will you be able to automatically add those? Note - COQ5 needs to be added to Mondo

**Comment by nicolevasilevsky** [comment]
Note to self- I will do this ^

**Pull request merged**
