### PR TITLE
Updating mass obsoletion workflow to prepend OBSOLETE to definitions

### PR DESCRIPTION
**Pull request by matentzn**
see https://github.com/monarch-initiative/mondo/issues/4474

@nicolevasilevsky I did not test this, just guessed it. Just try it, and if it does not work, we fix it in our next meeting.

### CODE REVIEW

**Comment by nicolevasilevsky** [comment]
I don't think this works (I went to this branch, then tried to run the command, is that the right thing to do?)

This is the error I get:

nicolevasilevsky@CHAI-M-C02FK38 ontology % sh run.sh make mass_obsolete2 -B
Running ODK with 8 GB of memory.
LISTT="MONDO:0020220 MONDO:0020218 MONDO:0016626 MONDO:0010113"; sed "s/MONDO:0000000/$LISTT/g" ../sparql/reports/mondo-obsolete-simple.sparql > tmp/mass_obsolete.sparql
robot --catalog catalog-v001.xml query -i mondo-edit.obo --use-graphs true -f tsv --query tmp/mass_obsolete.sparql tmp/mass_obsolete_me.txt
sed -i 's/[?]//g' tmp/mass_obsolete_me.txt
sed -i 's/<http:[/][/]purl[.]obolibrary[.]org[/]obo[/]MONDO_/MONDO:/g' tmp/mass_obsolete_me.txt
sed -i 's/>//g' tmp/mass_obsolete_me.txt
LISTT="MONDO:0020220 MONDO:0020218 MONDO:0016626 MONDO:0010113"; sed "s/MONDO:0000000/$LISTT/g" ../sparql/update/mondo-obsolete-simple.ru > tmp/mass_obsolete.ru
echo "Make sure you have updated ../sparql/update/mondo-obsolete-simple.ru before running this script.."
Make sure you have updated ../sparql/update/mondo-obsolete-simple.ru before running this script..
make mass_obsolete_warning
make[1]: Entering directory '/work/src/ontology'
LISTT="MONDO:0020220 MONDO:0020218 MONDO:0016626 MONDO:0010113"; sed "s/MONDO:0000000/$LISTT/g" ../sparql/reports/mondo-obsolete-warning.sparql > tmp/mass_obsolete_warning.sparql
robot --catalog catalog-v001.xml verify -i mondo-edit.obo --queries tmp/mass_obsolete_warning.sparql --output-dir reports/
FAIL Rule tmp/mass_obsolete_warning.sparql: 4 violation(s)
entity
http://purl.obolibrary.org/obo/MONDO_0020220
http://purl.obolibrary.org/obo/MONDO_0020218
http://purl.obolibrary.org/obo/MONDO_0016626
http://purl.obolibrary.org/obo/MONDO_0010113
make[1]: *** [mondo.Makefile:401: mass_obsolete_warning] Error 1
make[1]: Leaving directory '/work/src/ontology'
make: *** [mondo.Makefile:405: mass_obsolete2] Error 2
nicolevasilevsky@CHAI-M-C02FK38 ontology % sh run.sh make mass_obsolete2 -B
Running ODK with 8 GB of memory.
LISTT="MONDO:0020220 MONDO:0020218 MONDO:0016626 MONDO:0010113"; sed "s/MONDO:0000000/$LISTT/g" ../sparql/reports/mondo-obsolete-simple.sparql > tmp/mass_obsolete.sparql
robot --catalog catalog-v001.xml query -i mondo-edit.obo --use-graphs true -f tsv --query tmp/mass_obsolete.sparql tmp/mass_obsolete_me.txt
sed -i 's/[?]//g' tmp/mass_obsolete_me.txt
sed -i 's/<http:[/][/]purl[.]obolibrary[.]org[/]obo[/]MONDO_/MONDO:/g' tmp/mass_obsolete_me.txt
sed -i 's/>//g' tmp/mass_obsolete_me.txt
LISTT="MONDO:0020220 MONDO:0020218 MONDO:0016626 MONDO:0010113"; sed "s/MONDO:0000000/$LISTT/g" ../sparql/update/mondo-obsolete-simple.ru > tmp/mass_obsolete.ru
echo "Make sure you have updated ../sparql/update/mondo-obsolete-simple.ru before running this script.."
Make sure you have updated ../sparql/update/mondo-obsolete-simple.ru before running this script..
make mass_obsolete_warning
make[1]: Entering directory '/work/src/ontology'
LISTT="MONDO:0020220 MONDO:0020218 MONDO:0016626 MONDO:0010113"; sed "s/MONDO:0000000/$LISTT/g" ../sparql/reports/mondo-obsolete-warning.sparql > tmp/mass_obsolete_warning.sparql
robot --catalog catalog-v001.xml verify -i mondo-edit.obo --queries tmp/mass_obsolete_warning.sparql --output-dir reports/
PASS Rule tmp/mass_obsolete_warning.sparql: 0 violation(s)
make[1]: Leaving directory '/work/src/ontology'
robot --catalog catalog-v001.xml query -i mondo-edit.obo --use-graphs true --update tmp/mass_obsolete.ru \
	remove -T tmp/mass_obsolete_me.txt --axioms logical convert -f obo --check false -o mondo-edit.obo.obo
mv mondo-edit.obo.obo mondo-edit.obo
make NORM
make[1]: Entering directory '/work/src/ontology'
owltools --use-catalog  mondo-edit.obo --merge-axiom-annotations -o -f obo NORM.norm && robot --catalog catalog-v001.xml convert -i NORM.norm -o NORM.tmp.obo && mv NORM.tmp.obo NORM
make[1]: Leaving directory '/work/src/ontology'
mv NORM mondo-edit.obo
nicolevasilevsky@CHAI-M-C02FK38 ontology % sh run.sh make mass_obsolete2 -B
Running ODK with 8 GB of memory.
LISTT="MONDO:0020220 MONDO:0020218 MONDO:0016626 MONDO:0010113"; sed "s/MONDO:0000000/$LISTT/g" ../sparql/reports/mondo-obsolete-simple.sparql > tmp/mass_obsolete.sparql
robot --catalog catalog-v001.xml query -i mondo-edit.obo --use-graphs true -f tsv --query tmp/mass_obsolete.sparql tmp/mass_obsolete_me.txt
sed -i 's/[?]//g' tmp/mass_obsolete_me.txt
sed -i 's/<http:[/][/]purl[.]obolibrary[.]org[/]obo[/]MONDO_/MONDO:/g' tmp/mass_obsolete_me.txt
sed -i 's/>//g' tmp/mass_obsolete_me.txt
LISTT="MONDO:0020220 MONDO:0020218 MONDO:0016626 MONDO:0010113"; sed "s/MONDO:0000000/$LISTT/g" ../sparql/update/mondo-obsolete-simple.ru > tmp/mass_obsolete.ru
echo "Make sure you have updated ../sparql/update/mondo-obsolete-simple.ru before running this script.."
Make sure you have updated ../sparql/update/mondo-obsolete-simple.ru before running this script..
make mass_obsolete_warning
make[1]: Entering directory '/work/src/ontology'
LISTT="MONDO:0020220 MONDO:0020218 MONDO:0016626 MONDO:0010113"; sed "s/MONDO:0000000/$LISTT/g" ../sparql/reports/mondo-obsolete-warning.sparql > tmp/mass_obsolete_warning.sparql
robot --catalog catalog-v001.xml verify -i mondo-edit.obo --queries tmp/mass_obsolete_warning.sparql --output-dir reports/
FAIL Rule tmp/mass_obsolete_warning.sparql: 4 violation(s)
entity
http://purl.obolibrary.org/obo/MONDO_0020220
http://purl.obolibrary.org/obo/MONDO_0020218
http://purl.obolibrary.org/obo/MONDO_0016626
http://purl.obolibrary.org/obo/MONDO_0010113
make[1]: *** [mondo.Makefile:401: mass_obsolete_warning] Error 1
make[1]: Leaving directory '/work/src/ontology'
make: *** [mondo.Makefile:405: mass_obsolete2] Error 2

**Comment by matentzn** [comment]
This looks ok to me! As far as I can see, this is a QC error that is triggered when you try to obsolete a class that is not an obsoletion candidate. Can you verify that these four classes in the error message are actually obsoletion candidates?

So the command can only work if you have added legitimate (non-obsolete) obsoletion candidates!

**Comment by nicolevasilevsky** [comment]
Hm, I am still getting errors. Let's look at this together on Thurs.

**Comment by matentzn** [comment]
Did you want to mass obsolete something before the release?

**Comment by nicolevasilevsky** [comment]
No, everything should be done already for this month.

**Comment by matentzn** [comment]
@nicolevasilevsky ready for another try whenever.

**Review by nicolevasilevsky — APPROVED** [review]
This is working - woohoo! Thank you!

**Pull request merged**
