### PR TITLE
MONDO-NCIT module

### PR DESCRIPTION
**Pull request by matentzn**
Addresses https://github.com/monarch-initiative/mondo/issues/3130

Requires #3136 To be at least discussed for the renaming.

### CODE REVIEW

**Comment by nicolevasilevsky** [comment]
To me, this classification makes sense. I wonder if we should follow NCIT classify these terms in Mondo as they do in NCIT? If we asserted these parents, would this solve the problem?

Although we don't have 'testicular mixed embryonal carcinoma and teratoma' in Mondo and if we assert MONDO_0002599 teratocarcinoma to be a parent of 'childhood testicular mixed embryonal carcinoma', we'll have the single child problem.

**Comment by nicolevasilevsky** [comment]
To me, this classification makes sense. I wonder if we should follow NCIT classify these terms in Mondo as they do in NCIT? If we asserted these parents, would this solve the problem?

Although we don't have 'testicular mixed embryonal carcinoma and teratoma' in Mondo and if we assert MONDO_0002599 teratocarcinoma to be a parent of 'childhood testicular mixed embryonal carcinoma', we'll have the single child problem.

**Comment by matentzn** [comment]
This would require significant reclassification.. I count at least 111 such cases at the moment.. And I don't know if that's scalable in the long term..

**Comment by cmungall** [comment]
So I should clarify my step in #3130 
 - "And are not superclasses of any equivalent to a mondo class"

This should be"

 - "And are not superclasses of any equivalent to a mondo class, where superclass and equivalence is calculated using the merged ontology + equivalence axioms"

This should get NCITs that can *only* appear below MONDOs.

This is quite conservative, and it does by design filter out a lot of interesting intermediates. We definitely want to look at these interesting intermediates, and use boomer/symbiont to assist in repair - but that's another task!

**Comment by matentzn** [comment]
Hmm, I had a very nice workflow, but it relies on one thing: that I can select the NCIt roots from Mondo directly. The way I implemented it basically selects all mondo classes with equivalent NCIt classes that do not have any other mondo class equivalent to an NCIt class anywhere underneath it.. is this wrong?

**Comment by matentzn** [comment]
Alright, that is it. It "works" but it has two major downsides:

1. _It does not help use with our use case_: 26 out of 30 classes required by the use case do not make it into the module. Most of these are probably because they are actually intermediates that _should_ be in Mondo, but are not. I have implemented a [unit test](https://github.com/monarch-initiative/mondo/blob/mondo-ncit/src/sparql/unittest/ncit-cancer.sparql) that ensures that the resulting  mondo-ncit profile contains the 
2. Because of the [Reverse proxy problem](#3136)  I have to manually randomly omit two classes from the process:
```
sed -i '/^NCIT:C8748,/d' $@
sed -i '/^NCIT:C4752,/d' $@
```
Unless we want to rename both to the same Mondo ID? These seem different, not sure whether that would have the desired effects.

Please review the [current version](https://www.dropbox.com/s/19xhi0ycmfqmd6i/ncit-neoplasm-under-mondo.owl?dl=0) in Protege to get a rough sense of the shape of the mondo-ncit profile.

**Pull request closed without merging**
