### PR TITLE
update change.md

### PR DESCRIPTION
**Pull request by sabrinatoro**

### CODE REVIEW

**Comment by sabrinatoro** [comment]
@twhetzel please review and merge. 
This is the last piece of the release. It adds the summary of changes to [changes.md](https://github.com/monarch-initiative/mondo/blob/master/Changes.md).

**Comment by twhetzel** [comment]
I was out sick yesterday. Was this not updated?

**Comment by sabrinatoro** [comment]
I don't know what you mean by "updated".
The PR was created to update the change.md file and the PR needs to be reviewed and merged. 
(note that we could make a decision this PR can be merged without review moving forward)

**Comment by twhetzel** [comment]
updated --> re-assigned to someone else so it would be merged for the release since I was no longer available

**Review by twhetzel — APPROVED** [review]
lgtm

**Pull request merged**
