### PR TITLE
test some gene-related non human animal diseases

### PR DESCRIPTION
**Pull request by sabrinatoro**
@matentzn
In order to make sure that the non-human genes did not refer to human gene with the same gene symbol, I used the gene IRI. And it worked. However, in protege, the associated gene refers to the human gene and not the non-human gene (despite the mondo-edit.obo being correct for what I can tell

### CODE REVIEW

**Comment by matentzn** [comment]
This looks great! Dont rely on what you see in protege. Protege uses label-based linking, so when you click on a label in a definition for example, it will bring you to a random class with that label - not the one you actually used in that axiom!

What matters is what you see in OBO

**Comment by sabrinatoro** [comment]
In summary: the spreadsheet and mondo-edit show the non-human gene, and use the correct IRI for the non-human gene. However, Protege redirect to the human gene when the gene has the same name in human and non-human. 
Though both human and non-human genes are present in protege.

See "TESTCopy ROBOT species specific genetic diseases" tab in [this spreadsheet](https://docs.google.com/spreadsheets/d/1aKuKc2yKy4Z1_yzntsOSi-Z-2V_AMKdmcwOZsVpUwtM/edit?gid=1364623127#gid=1364623127).

Protege screenshots: 
Screenshot 2024-07-22 at 10 45 14 AM

When rendering by entity IRI:
Screenshot 2024-07-22 at 10 49 11 AM


When clicking on "CHAT":
Screenshot 2024-07-22 at 10 46 07 AM

Though in mondo-edit: 

Screenshot 2024-07-22 at 10 48 11 AM

**Comment by sabrinatoro** [comment]
@katiermullen, please see Nico's comment above.

**Comment by katiermullen** [comment]
@matentzn @sabrinatoro Thank you so much for taking a look at this and explaining the issue to me! I am now completely unstuck and will be able to add more non-human animal genetic diseases to Mondo from OMIA. Hooray!

**Comment by sabrinatoro** [comment]
This is fantastic @katiermullen !! 
If you think these PRs can be closed, please do so. 
And as always, please reach out if you have any other questions!

**Comment by katiermullen** [comment]
@sabrinatoro just confirming that you would like me to: 
1. Close this draft PR as well as the draft PR https://github.com/monarch-initiative/mondo/pull/7949.
2. Create a new PR for the animal genetic diseases that I will assign to you for review and merging.

**Comment by sabrinatoro** [comment]
@katiermullen 
There are 2 PRs: 
- https://github.com/monarch-initiative/mondo/pull/7949
- https://github.com/monarch-initiative/mondo/pull/7987
Both were marked as tests, but I don't know whether you wanted them to be "only" tests or if you wanted to merge them.

So whatever you decide, these PRs above should be either closed (if they were only for test purposes) or merged.

**Pull request closed without merging**
