### PR TITLE
add new COVID-19 terms/revise the hierarchy

### LINKED ISSUE #2896: revisions to COVID-19 hierarchy
Regarding current classification, from @cmungall 
is this the correct placement of long COVID-19? Is long covid a subtype of covid, or a consequence of it? We have a class 'post-viral disorder' where we have things like shingles (of course, long covid may not be a reactivation in the same way but the general principles re subtypes vs sequelae should apply)

proposed hierarchy from @pnrobinson:

SARS-CoV-2 infectious disease
-'acute COVID-19'
--'critical COVID-19 infection'
--'mild COVID-19 infection'
--'moderate COVID-19 infection'
--'presymptomatic COVID-19 infection'
--'severe COVID-19 infection'
-'long COVID-19'
-'MIS-A'
-'MIS-C'

### PR DESCRIPTION
**Pull request by nicolevasilevsky**
fix #2896

### CODE REVIEW

**Comment by nicolevasilevsky** [comment]
image

**Comment by nicolevasilevsky** [comment]
the hierarchy needs review, as well as the logical defs (which I am unsure about) and the text defs
@cmungall @mellybelly @pnrobinson

**Comment by cmungall** [comment]
The general pattern is

 * X or sequela-of X
     * X
     * sequela-of X

where the children are JEPD, and placement of everything is known, ie they should have no direct sibs, ie long COVID etc would go under sequela

**Comment by nicolevasilevsky** [comment]
JEPD = Jointly Exhaustive Pairwise Disjoint?

I revised this to:
I think some of the logic is over my head though! I'm still unclear about the design pattern (see PR: #2903)

image

**Comment by nicolevasilevsky** [comment]
Current hierarchy:
image

**Pull request merged**
