### PR TITLE
Remove places where UMLS:CN was used as evidence

### PR DESCRIPTION
**Pull request by matentzn**
There are 59 places where UMLS:CN was used as evidence. CN are temporary CUIs minted by Medgen, and we have no way to track them - so we should not use them as evidence. They are not in UMLS.

### CODE REVIEW

**Comment by matentzn** [comment]
cc @joeflack4 FYI

**Comment by joeflack4** [comment]
Hmm I thought UIDs were more transient than CNs (CUI Novels), but you are probably right.

Just to clarify, what precisely am I looking to delete?

I'm thinking it is this pattern?
`xref: XYZ:123 {source="UMLS:CN12345"}`

Or is there an IAO or some other predicate that has some meaning like "has_evidence"?

**Comment by matentzn** [comment]
? This is a pull request that already deals with the issue! No need for you to do anything!

**Comment by joeflack4** [comment]
Yeah maybe I should have just deleted that question; I had wrote later:
> edit: Oh, this is a PR, not an issue, lol.I see what you have done.

**Review by sabrinatoro — APPROVED** [review]

**Pull request merged**
