### PR TITLE
Adding abbreviation annotations to all synonyms which are abbreviations

### PR DESCRIPTION
**Pull request by matentzn**
As there are more than 3K of these, I took a simplifying assumption:

This is the search string:

```
^(synonym: "[A-Z]+["][0-9: a-zA-Z\[\],/\.-_\-]*)$
```

This is is the replace string for Atom:

```
$1 {synonymtypedef="ABBREVIATION"}
```

### CODE REVIEW

**Comment by nicolevasilevsky** [comment]
@matentzn I can't view this diff. When I'm back from TG, can you show me an (easier) way of looking at this? Thanks!

**Comment by matentzn** [comment]
GitHub desktop! Just go to the branch and click on the last commit in the history.

**Comment by nicolevasilevsky** [comment]
Ugh, @matentzn this isn't done correctly, I tried to fix one example and it created a ton of conflicts. I reverted my commit, but there are still conflicts.

So this isn't done correctly - it should look like this
synonym: "ALS" EXACT ABBREVIATION [DOID:332, NCIT:C34373, Orphanet:803]

**Comment by matentzn** [comment]
No problem will fix soon

**Comment by matentzn** [comment]
I will make a new one

**Pull request closed without merging**
