### PR TITLE
ready for review: obsolete children of infectious disease

### PR DESCRIPTION
**Pull request by nicolevasilevsky**
infectious, fungal or parasitic myopathy
inherited prion disease
sporadic human prion disease

close https://github.com/monarch-initiative/mondo/issues/6671

Janani Ravi said she would like to discuss this, will wait to merge

### CODE REVIEW

**Comment by nicolevasilevsky** [comment]
@twhetzel @sabrinatoro - this is the last PR from my initial mass obsoletion efforts but maybe we should hold off on the review/merge until we've worked on some of the other tables? This now has conflicts that need to be fixed, not sure when the best time to work on this will be.

I talked to Janini today and she had questions about the infectious disease modeling overall but did not have any issues with this PR.

**Comment by twhetzel** [comment]
@nicolevasilevsky - can we set this back to a Draft PR and/or change it's title?

**Comment by nicolevasilevsky** [comment]
sure! I'll make it a draft. In the future, feel free to do so yourself too (and you can just tag me in a comment)

**Comment by sabrinatoro** [comment]
At this point, there will be too many conflicts to resolve. Closing this in favor of reviewing the spreadsheet

**Pull request closed without merging**
