### PR TITLE
add `free` command to see docker memory profile when its run

### PR DESCRIPTION
**Pull request by dougli1sqrd**

### CODE REVIEW

**Comment by cmungall** [comment]
Any closer to this @dougli1sqrd? Maybe the SPARQL can be written in a more efficient way? Or should we just have a special purpose procedure in ROBOT, cc @balhoff

**Comment by balhoff** [comment]
What’s this related to? I don’t see anything linked.

**Comment by balhoff** [comment]
I can't find any way to speed up the SPARQL.

**Comment by balhoff** [comment]
I did notice that the `robot` commands in the MONDO makefile don't seem to have `ROBOT_JAVA_ARGS` specified. That didn't make a difference on my laptop, but is it possible the Travis default max heap is smaller?

**Comment by dougli1sqrd** [comment]
The latest commit cleans up the travis config. At this point this travis run should clear and we should be good.

**Pull request merged**
