### PR TITLE
create page for Epilepsy workshop

### PR DESCRIPTION
**Pull request by nicolevasilevsky**

### CODE REVIEW

**Comment by twhetzel** [comment]
@nicolevasilevsky is this ready for review or are you still making changes?

**Comment by nicolevasilevsky** [comment]
it's ready, thanks @twhetzel

**Review by twhetzel — APPROVED** [review]
I ran the web site locally and reviewed the page. All looks good!

**Comment by twhetzel** [comment]
The update is deployed: https://mondo.monarchinitiative.org/pages/workshop/#Oct-2024

**Pull request merged**
