### PR TITLE
added non-human animal neoplasm terms from NCIT

### PR DESCRIPTION
**Pull request by sabrinatoro**
Addresses #5252

### CODE REVIEW

**Comment by sabrinatoro** [comment]
@matentzn 
This PR adds new non-human animal neoplasm terms from NCIT. 
I use "MONDO:equivalentTo" because these terms in Mondo are equivalent to the NCIT terms (ie the NCIT terms are actual diseases). However, these are not in the "human disease" hierarchy. 
Do you think it is the correct annotation? Or should we use "MONDO:otherHierarchy" like we did for the AML terms? (There might be other consequences to not use "MONDO:equivalentTo", but I'll way for your feedback before getting there)
Thank you!

**Comment by matentzn** [comment]
@sabrinatoro I think equivalentTo is correct - AML was different - they were not really diseases. :)

**Comment by sabrinatoro** [comment]
note: I will normalize after this PR is accepted

**Review by nicolevasilevsky — APPROVED** [review]

**Comment by nicolevasilevsky** [comment]
This looks good to me. @sabrinatoro do you want to merge? Sounds like you want to run make norm first?

**Pull request merged**
