### PR TITLE
ICD10 mapping - add xrefs

### PR DESCRIPTION
**Pull request by nicolevasilevsky**
@matentzn I reviewed the ICD10 mappings and added new ICD10 xrefs to Mondo.

I have a list of mappings I didn't agree with [here](https://docs.google.com/spreadsheets/d/1uy0G5pCTmIhentKN8YNO8z684_mAJdnFQQZ_4kDlr3U/edit#gid=33930573).

cc @joeflack4 @hrshdhgd 

address https://github.com/monarch-initiative/mondo-ingest/issues/78

### CODE REVIEW

**Comment by matentzn** [comment]
Hey @nicolevasilevsky can you perhaps assign someone else for the review - this seems mostly about content, not really structure right?

**Comment by nicolevasilevsky** [comment]
I want to review this again:
https://docs.google.com/spreadsheets/d/1uy0G5pCTmIhentKN8YNO8z684_mAJdnFQQZ_4kDlr3U/edit#gid=254108608

**Comment by nicolevasilevsky** [comment]
@matentzn is this something we should still work on or should we close this?

**Comment by matentzn** [comment]
We should absolutely deal with this PR, but it has been to long for me to know what needs doing exactly. Unfortunately you will have to figure out somehow what the context was and how to fix it :(

**Comment by nicolevasilevsky** [comment]
ok, I will add it to my to-do list

**Comment by nicolevasilevsky** [comment]
these are ICD10 code that are not exact matches on the label. The open question is if these are indeed proper exact matches. In the case of 'no', we would need to revise the lexical matching pipeline to handle the non-exact matches, or they would need to be manually reviewed.

**Comment by nicolevasilevsky** [comment]
we are closing this, it is too complex of a task and this is not on our road map right now

**Pull request closed without merging**
