### PR TITLE
removing injury branch from under disease

### PR DESCRIPTION
**Pull request by cmungall**
I thought we had an issue for this, I can find ancillary tickets like #499

This places injury at root, it doesn't belong under disease

We can

1. leave at root and add an exception to the hardcoded list of roots in the test
2. place directly under material entity
3. place under ogms:disorder (which is a subclass of material entity)

### CODE REVIEW

**Comment by nicolevasilevsky** [comment]
I feel like we talk about this before too but I don't see any notes about it in our curation call minutes either.

I agree with moving it out the disease branch. I am not sure about the best place to put it. @sabrinatoro @matentzn, do you have opinions?

**Comment by sabrinatoro** [comment]
I agree that it makes sense to remove "injury" from the disease branch. 
I remember we talked about it, but I don't remember what we said. I think it is important to find "why" we decided to have an "injury" branch in Mondo at all (I will also do some research in my notes). 
Looking at the branch, there are "ulcer disease" and "acute radiation syndrome" which appear to be the only actual diseases. We should review and make sure that these, if we believe they are actual diseases, are somewhere else in the disease branch.

**Comment by cmungall** [comment]
one thing at a time. This PR doesn't remove injury. It just changes the parent

**Comment by nicolevasilevsky** [comment]
I meant to say, if we remove injury from the disease branch. But the terms would still be accessible to users, right, in the same way as a disease susceptibility? I can't think of any objections to that. I agree with @sabrinatoro that we should move poisonings out of the disease branch too.

**Comment by joeflack4** [comment]
Just me being curious here. Does it make sense to have a common parent for diseases and injuries? Something like "affliction"?

**Comment by nicolevasilevsky** [comment]
If there are no objections from the community to this change, we'll implement these changes next week (on/after Monday, 2023-03-20)

**Comment by kanems** [comment]
no objections from the MedGen team to moving Injury outside of the disease concept. Thanks for the heads up.

**Comment by nicolevasilevsky** [comment]
> no objections from the MedGen team to moving Injury outside of the disease concept. Thanks for the heads up.

**Comment by nicolevasilevsky** [comment]
I closed this by accident, reopening

**Comment by nicolevasilevsky** [comment]
We agreed that we will proceed with this PR. @matentzn could you adjust the QC check to allow the injury branch to be at root? Thanks!

**Comment by matentzn** [comment]
@sabrinatoro can you fix what @nicolevasilevsky is asking for? This is the line: https://github.com/monarch-initiative/mondo/blob/master/src/sparql/qc/mondo/qc-no-superclass.sparql#L24

**Comment by matentzn** [comment]
sparql looks good but there are conflicts in edit file

**Comment by nicolevasilevsky** [comment]
> sparql looks good but there are conflicts in edit file

I will fix. Thanks @matentzn and @sabrinatoro!

**Review by nicolevasilevsky — APPROVED** [review]

**Pull request merged**
