### PR TITLE
Close this: add xref to MONDO_0021060 RASopathy

### LINKED ISSUE #606: Merge request for RASopathy + Noonan Syndrome and Noonan-related Syndrome
For new term requests, please provide the following information:

There are two terms
[MONDO:0021060](https://monarchinitiative.org/disease/MONDO:0021060) (RASopathy) with no equivalent ids
and
[MONDO:0020297](https://monarchinitiative.org/disease/MONDO:0020297) (Noonan Syndrome and Noonan-Related Syndromes) which originates from [Orphanet:98733](http://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=en&Expert=98733)

The ClinGen consortium's RASopathy Variant Curation Expert Panel relies on MONDO with their tooling to perform expert curations in this domain. When curation users lookup 'RASopathy' in MONDO they get the first MONDO id above.  However, the end result needs to be shared in ClinVar. Since ClinVar is driven by MedGen and not MONDO, they map the "Orphanet:98733" term to "RASopathy" as an equivalent.  ClinVar requires the submitters to use MedGen or Orphanet or OMIM or MeSH ids during submission. The ClinGen tooling is designed to rely on MONDO's equivalent ids to find a match that is suitable for ClinVar.

When we hit situations like this, we think it would be best for the overall community to be able to work with the resource that is able to provide the best solution. We request that MONDO merge these two terms as they appear to be equivalent or make the argument for keeping them separate and thus requesting Orphanet or OMIM to create an equivalent term that would allow better harmony with downstream system's like ClinVar and ClinGen.

Please let us know if this is possible.

### PR DESCRIPTION
**Pull request by nicolevasilevsky**
closes #606

### CODE REVIEW

**Comment by nicolevasilevsky** [comment]
yes - done! Let me know if there are any issues

**Comment by nicolevasilevsky** [comment]
pinging @ShahimEssaid re: the comment about travis

@cmungall is there any other action for me?

**Comment by nicolevasilevsky** [comment]
@cmungall can this be merged?

**Comment by cmungall** [comment]
changes to travis.yml should be done in a separate PR

Make a new PR for the xref then close this

**Pull request closed without merging**
