### PR TITLE
Ontobot can now read commands from issue comments

### LINKED ISSUE #7853: Reconfigure ontobot to allow for directives to be acted on from any comment, not just top comment
E.g

https://github.com/monarch-initiative/mondo/issues/7723#issuecomment-2190038967

### LINKED ISSUE #7871: Ontobot created PRs need to trigger the QC Check GH Action
When ontobot creates a PR, the `ontology_qc` GH Action also needs to run. This should happen regardless of whether the ontobot triggered PR is from an issue submitted here in the Mondo issue tracker or submitted through BioPortal (just mentioning this for completeness).

### PR DESCRIPTION
**Pull request by hrshdhgd**
Fixes #7853 

In the past, `ontobot-change-agent` only processed the text in the issue body to look for `Hey ontobot, apply:`.

With this PR, it not only does that but also looks for comments that have KGCL commands starting with the phrase above. The latest comment containing the command takes precedence.

The latest version of `ontobot-change-agent` (v0.4.12) is capable of doing so and the workflow update in this PR facilitates for the smooth transition to getting the new feature.

**Update**: Also installed `ontobot-change-agent` (a GitHub app) to run QCs. Fixes #7871

### CODE REVIEW

**Review by cmungall — APPROVED** [review]

**Review by twhetzel — APPROVED** [review]
Looks good to me. I'll leave open for @matentzn and @sabrinatoro to review.

**Comment by sabrinatoro** [comment]
I do not know how to test this because I don't know how to an issue in the context of this specific branch.

I think we can just merge, and test after it is merged.

**Review by matentzn — COMMENTED** [review]
Unfortunately I do not have the bandwidth to review this in any detail. I would suggest the following SOP for such PRs:

1. @twhetzel eyeball-reviews, looking out for commands / processes that risk deleting the internet (`rm -rf /internet`)
2. The pull request maker provides a quick instruction on how the PR can be tested.

I dont see any major issues or anything, but I also just cant be sure.

**Comment by hrshdhgd** [comment]
This PR can only be tested after merging it unfortunately.

How to test?
-------

 - Open a new issue
 - Write anything in the body doesn't matter
 - Add this as comment after the issue is created

```
Hey Ontobot! apply:

- create narrow synonym 'Low-flow priapism(test)' for MONDO:0004745
```

This should trigger the workflow to generate a PR. The PR is generated under the name `ontobot-change-agent` and this should trigger QC workflows for this repository.

I have[ tested this in my fork](https://github.com/hrshdhgd/mondo/issues/30) to make sure the internet isn't wiped clean!

**Comment by hrshdhgd** [comment]
One way of testing this is:

 - Fork MONDO 
 - Copy paste the workflow file into your fork's `ontobot.yml` file
 - Follow the instructions above.

**Comment by twhetzel** [comment]
I reviewed again and tested in Harshad's repo and all still looks good.

**Pull request merged**
