### PR TITLE
Release July 2024

### PR DESCRIPTION
**Pull request by sabrinatoro**
Mondo_release_diff: 
[mondo_release_diff.md](https://github.com/user-attachments/files/16070653/mondo_release_diff.md)

### CODE REVIEW

**Comment by sabrinatoro** [comment]
@twhetzel this PR is ready for your review.

**Review by twhetzel — COMMENTED** [review]
Overall I think it looks ok, but there are some files with a large number of changes in files in "reports", e.g. `reports/superclass-count.tsv`, `reports/xrefs.tsv`. Are these expected?

Also, I don't see this file `src/ontology/reports/mondo_obsoletioncandidates.tsv`.

**Comment by sabrinatoro** [comment]
I am looking into this now
@matentzn , tagging you as you might have quicker insight.

**Comment by sabrinatoro** [comment]
I do see this file:  src/ontology/reports/mondo_obsoletioncandidates.tsv
Screenshot 2024-07-02 at 10 35 43 AM

We added new xref (e.g MedGen x-ref), and we changed exactMatch to skos:exactMatch. 
The changes are expected.

**Comment by twhetzel** [comment]
@sabrinatoro there is an open question on Slack whether changes are needed. Let me know if you prefer I approve the PR in the meantime and then you track completion of that discussion. Otherwise, I'll leave this as not approved yet and will continue to track the discussion.

**Review by twhetzel — APPROVED** [review]
Approving following resolving Slack conversations.

**Pull request merged**
