### PR TITLE
replace seeAlso with term tracker item

### PR DESCRIPTION
**Pull request by nicolevasilevsky**
close #5315

### CODE REVIEW

**Comment by matentzn** [comment]
Its generally correct, but seems to me there are still seeAlso in there

image

**Comment by matentzn** [comment]
```
property_value: seeAlso https://github.com/monarch-initiative/hpo-annotation-data/issues/260 xsd:anyURI
```

Maybe its because xsd:anyURI?

**Comment by nicolevasilevsky** [comment]
ah, thanks for catching that! I think I got them all now

**Comment by matentzn** [comment]
did you also run NORM again?

**Comment by nicolevasilevsky** [comment]
no, I'll do it now!

**Pull request merged**
