### PR TITLE
acquired/inherited relation with gene

### PR DESCRIPTION
**Pull request by sabrinatoro**
addresses #4675

### CODE REVIEW

**Comment by sabrinatoro** [comment]
@matentzn : this PR is failing because : 
FAIL Rule ../sparql/qc/mondo/qc-omimps-should-be-inherited.sparql: 1 violation(s)
entity,property,value
http://purl.obolibrary.org/obo/MONDO_0[10](https://github.com/monarch-initiative/mondo/runs/6100911796?check_suite_focus=true#step:4:10)0244,http://purl.obolibrary.org/obo/RO_0002573,

Background: some omim/omimPS terms could be acquired. Therefore I updated the patterns and the QC to reflect that the relation to a gene could be "has material basis in somatic mutation in" or "has material basis in germline mutation in". I also updated the GCA to indicate that  "has material basis in germline mutation in" some gene (instead of "disease has basis in dysfunction some gene") should also have the inherited modifier. 
 
In this case the QC is specifically to check that a term with omimps has to be "inherited", which is not correct anymore. 
I am not sure how to proceed. Should we 1) remove this QC all together, or 2) update the QC such that it says that IF the omimPS has children with omim "inherited", then it should be inherited? 
Thank you!

**Comment by matentzn** [comment]
Please raise in QC call or next 1:1

**Comment by sabrinatoro** [comment]
@matentzn 
This PR is still failing due to the "FAIL Rule ../sparql/qc/mondo/qc-omimps-should-be-inherited.sparql"
I added the "exclude from" this QC, and we updated the sparql to allow this "exclude from" in another PR (and I checked the sparql query and cannot find anything wrong).
I cannot figure out why I keep on getting the same QC fail. 
Should I do something to make sure that the updated QC is taken into consideration? 
Thank you!

**Comment by sabrinatoro** [comment]
UPDATE: I think there might be another (sneaky) typo in the sparql

**Comment by matentzn** [comment]
too many changes in the diff.. risky. Update from master and make sure you add the sparql query correctly. Share protege screen shot of exclusion annotation?

**Review by nicolevasilevsky — APPROVED** [review]

**Pull request merged**
