### PR TITLE
mass obsoletion: inflammatory branch

### LINKED ISSUE #6748: Mass Obsoletion: focus on branch 'inflammatory disease' (MONDO:0021166)
branch : 'inflammatory disease' (MONDO:0021166)

Terms to obsolete: 

obsoletion candidate ID | obsoletion candidate label
-- | --
http://purl.obolibrary.org/obo/MONDO_0015144 | brain inflammatory disease
http://purl.obolibrary.org/obo/MONDO_0020069 | chronic encephalitis
http://purl.obolibrary.org/obo/MONDO_0033947 | hereditary angioedema with normal C1Inh
http://purl.obolibrary.org/obo/MONDO_0015591 | limbic encephalitis associated with antibodies to cell membrane antigens
http://purl.obolibrary.org/obo/MONDO_0019541 | non-infectious posterior uveitis
http://purl.obolibrary.org/obo/MONDO_0020537 | occupational allergic alveolitis
http://purl.obolibrary.org/obo/MONDO_0015488 | predominantly large-vessel vasculitis
http://purl.obolibrary.org/obo/MONDO_0015489 | predominantly medium-vessel vasculitis
http://purl.obolibrary.org/obo/MONDO_0015490 | predominantly small-vessel vasculitis
http://purl.obolibrary.org/obo/MONDO_0018745 | superficial pemphigus

Removed from obsoletion list (see [comment below](https://github.com/monarch-initiative/mondo/issues/6748#issuecomment-1771985312))
obsoletion candidate ID | obsoletion candidate label
-- | --
http://purl.obolibrary.org/obo/MONDO_0018640 | secondary vasculitis

- [x] we need to remove the obsoletion tag from this term

### PR DESCRIPTION
**Pull request by sabrinatoro**
Addresses #6748

### CODE REVIEW

**Comment by sabrinatoro** [comment]
First PR added parents

**Comment by sabrinatoro** [comment]
@nicolevasilevsky and @twhetzel This mass obsoletion is done and ready for final review from both of you. 
Please add your review BUT do not merge until you both had a chance to take a look.

@twhetzel I took this PR opportunity to review the mass obsoletion pipeline and all the latest updates. I didn't see anything wrong, and everything seemed to work as expected. Thank you!

**Review by nicolevasilevsky — APPROVED** [review]
this looks good to me, I don't see any issues. Great job!

**Comment by twhetzel** [comment]
Reviewing now...

**Review by twhetzel — APPROVED** [review]
Looks good and also confirmed the previously obsoleted terms have this issue number annotation added, e.g. "obsolete chronic encephalitis", "obsolete occupational allergic alveolitis".

**Comment by sabrinatoro** [comment]
Awesome, thank you!!! 
I will merge now.

**Pull request merged**
