### PR TITLE
remove superclasses for MONDO:0008608 down syndrome. Addresses #824

### PR DESCRIPTION
**Pull request by nicolevasilevsky**
per discussion with @paolaroncaglia on the Mondo/EFO call today, she advised me to remove several of the superclasses for down syndrome.

The diff was really huge, and it won't let me see it in GitHub, so here is a screenshot of part of it:

image

I don't think there are unintended changes- I don't know why it is doing that? @cmungall or @ShahimEssaid do you have any idea why I am getting these weird diffs?

### CODE REVIEW

**Comment by cmungall** [comment]
Which version of Protege?

**Comment by nicolevasilevsky** [comment]
v5.5

**Comment by cmungall** [comment]
OK, it looks like somehow a non-canonical serialization was merged to master

**Comment by cmungall** [comment]
Remember, don't commit if you see a large unexpected diff. A diff with a few `!` labels is fine if imports out of sync.

If this happens it means someone is out of sync. If it is master It makes most sense to normalize first, then re-branch and make changes from then

should be in guide

**Comment by nicolevasilevsky** [comment]
ok, I can close this PR and redo this.

how do you normalize master?

**Pull request closed without merging**
