### PR TITLE
nonhuman test01 cjm suggestions

### PR DESCRIPTION
**Pull request by cmungall**
- (do not review at this moment) non-human proposal
- added species parents based on Taxon
- Update mondo-edit.obo
- Adding disjointness
- Suggested axiomatization

### CODE REVIEW

**Comment by cmungall** [comment]
`git diff nonhuman-test01 mondo-edit.obo`


```
diff --git a/src/ontology/mondo-edit.obo b/src/ontology/mondo-edit.obo
index a5a402ea..be36bbf8 100644
--- a/src/ontology/mondo-edit.obo
+++ b/src/ontology/mondo-edit.obo
@@ -96207,6 +96207,7 @@ xref: EFO:0005932 {source="MONDO:equivalentTo"}
 xref: MESH:D000820 {source="MONDO:equivalentTo"}
 xref: UMLS:C0003047 {source="MONDO:equivalentTo"}
 is_a: MONDO:0000001 {source="EFO:0005932"} ! disease or disorder
+disjoint_from: MONDO:0700096 ! human disease or disorder
 relationship: never_in_taxon NCBITaxon:9606 ! Homo sapiens

 [Term]
@@ -420297,6 +420298,8 @@ synonym: "diseases, Bird" RELATED [MESH:D001715]
 xref: MESH:D001715 {source="MONDO:equivalentTo"}
 xref: UMLS:C0005591 {source="MONDO:equivalentTo"}
 is_a: MONDO:0005583 {source="MESH:D001715"} ! non-human animal disease
+intersection_of: MONDO:0000001 ! disease or disorder
+intersection_of: in_taxon NCBITaxon:8782 ! Aves
 relationship: in_taxon NCBITaxon:8782 {source="https://orcid.org/0000-0002-4142-7153", source="https://orcid.org/0000-0002-5002-8648"} ! Aves

 [Term]
@@ -420590,6 +420593,7 @@ replaced_by: MONDO:0011558
 id: MONDO:0025003
 name: goat disease
 def: "Diseases of the domestic or wild goat of the genus Capra." [MESH:D015511]
+comment: Consider obsoleting this, as it groups other non-goat diseases
 synonym: "caprine disease" RELATED [MESH:D015511]
 synonym: "caprine diseases" RELATED [MESH:D015511]
 synonym: "disease, caprine" RELATED [MESH:D015511]
@@ -456554,6 +456558,8 @@ created_by: http://orcid.org/0000-0002-4142-7153
 id: MONDO:0700096
 name: human disease or disorder
 is_a: MONDO:0000001 ! disease or disorder
+intersection_of: MONDO:0000001 ! disease or disorder
+intersection_of: in_taxon NCBITaxon:9606 ! Homo sapiens
 property_value: RO:0002175 NCBITaxon:9606
 created_by: http://orcid.org/0000-0002-4142-7153

@@ -456617,6 +456623,8 @@ created_by: http://orcid.org/0000-0002-4142-7153
 id: MONDO:0700106
 name: immune system disorder, non-human
 is_a: MONDO:0005583 ! non-human animal disease
+intersection_of: MONDO:0000001 ! disease or disorder
+intersection_of: MONDO:0700097 MONDO:0005046 ! cross-species analog immune system disorder, human
 relationship: MONDO:0700097 MONDO:0005046 ! cross-species analog immune system disorder, human
 created_by: http://orcid.org/0000-0002-4142-7153

```

**Comment by sabrinatoro** [comment]
@cmungall and @nicolevasilevsky 
I made more changes, added axioms, and reviewed the classes that were problematic. 
If you agree and if you don't see other issues, I think we could merge this PR. 

Still to do (though I think it can wait until next release), in addition to adding definitions to new non-human disease terms: review the infectious disease branch, especially the terms that groups infectious diseases by the infectious sites (e.g. "skin infection"). I took care of the terms that were problematic, but I still need to review the rest of the branch. 
(And also, I am aware that I need to document patterns... but I will do it later.)

**Review by nicolevasilevsky — APPROVED** [review]

**Comment by nicolevasilevsky** [comment]
this looks great to me! This is so exciting, great work @sabrinatoro!

**Comment by sabrinatoro** [comment]
Thank you @nicolevasilevsky 
Can we merge? or should we wait for @cmungall feedback?

**Comment by nicolevasilevsky** [comment]
@sabrinatoro It would be great to get approval from Chris too. Please ping him on Slack, thanks!

**Pull request merged**
