### PR TITLE
travis passed: ntr small intestinal bacterial overgrowth issue #769

### PR DESCRIPTION
**Pull request by laurenechan**
Addition of small intestinal bacterial overgrowth to the ontology. Additional information in issue #769

### CODE REVIEW

**Comment by nicolevasilevsky** [comment]
@cmungall I resolved the conflicts here. It is ready for your review/ready to merge

**Comment by cmungall** [comment]
conflicts :-(

**Comment by cmungall** [comment]
conflict...

**Comment by matentzn** [comment]
Conflicts resolved.

**Pull request merged**
