### PR TITLE
edited subclassOf axiom on MONDO:0017979. 

### PR DESCRIPTION
**Pull request by nicolevasilevsky**
I edited the subclassOf axiom- changed it to disease_has_feature_ some 'neoplastic syndrome'

Is this correct?

addresses #530

### CODE REVIEW

**Comment by cmungall** [comment]
I believe it is a neoplastic syndrome; such syndromes have features that are neoplasms of various sorts

**Comment by nicolevasilevsky** [comment]
Thanks - is this okay to merge then?

**Comment by cmungall** [comment]
no, the existing is_a is fine I think (if this is generally considered a neoplastic syndrome), it's the is_a tumor that needs changed

**Comment by nicolevasilevsky** [comment]
Oh, I see, thanks for clarifying! I am going to close this PR then and create a new one.

**Pull request closed without merging**
