### PR TITLE
add new term MONDO_0100076 'juvenile idiopathic scoliosis'. 

### LINKED ISSUE #694: NTR: Juvenile Idiopathic Scoliosis
For new term requests, please provide the following information:

## Preferred term label

juvenile idiopathic scoliosis

## Synonyms

N/A

## Textual definition

A scoliosis with no known cause arising in a juvenile.

## Suggested parent term

MONDO_0000726 idiopathic scoliosis

## Attribution

https://orcid.org/0000-0001-5208-3432

### PR DESCRIPTION
**Pull request by nicolevasilevsky**
Closes #694

### CODE REVIEW

**Comment by nicolevasilevsky** [comment]
@cmungall I added a logical def, I don't see a juvenile.yaml in https://github.com/monarch-initiative/mondo/tree/master/src/patterns though.

**Comment by nicolevasilevsky** [comment]
(I just followed an example on a similar term. I can create a juvenille.yaml pattern if needed)

**Comment by cmungall** [comment]
Can you resolve conflicts?

**Comment by nicolevasilevsky** [comment]
@cmungall the conflicts have been addressed

**Pull request merged**
