### PR TITLE
ntr calcium-alkali syndrome issue #771

### PR DESCRIPTION
**Pull request by laurenechan**
Calcium-alkali syndrome added, more info in the issue #771

### CODE REVIEW

**Comment by nicolevasilevsky** [comment]
@cmungall I resolved the conflicts, this should be ready to merge

**Comment by cmungall** [comment]
conflict... also weird ID issue

**Comment by matentzn** [comment]
Will fix this.

**Comment by matentzn** [comment]
Its fixed. Can be merged.

**Pull request merged**
