### PR TITLE
update ncbi import

### PR DESCRIPTION
**Pull request by twhetzel**
addresses https://github.com/monarch-initiative/mondo/issues/7343

I updated the imports as mentioned [here](https://github.com/monarch-initiative/mondo/issues/7343#issuecomment-1977999536).

### CODE REVIEW

**Review by nicolevasilevsky — APPROVED** [review]
thanks @twhetzel!

**Comment by twhetzel** [comment]
@nicolevasilevsky please confirm the steps I [ran](https://github.com/monarch-initiative/mondo/issues/7343#issuecomment-1977999536) are correct!

**Comment by nicolevasilevsky** [comment]
this looks correct to me

**Comment by twhetzel** [comment]
Thanks @nicolevasilevsky! I also asked on Slack and @matentzn mentioned:
```
Yes, these steps are correct with a small but important caveat: we are not using NCBI taxon directly, but the OBO slim of it. So whatever taxon you want to reuse must be present in this file:
https://github.com/obophenotype/ncbitaxon/blob/master/subsets/taxon-subset-ids.txt
which is the seed of the ncbitaxon slim.
```

I submitted a ticket to have this added: https://github.com/obophenotype/ncbitaxon/issues/100

**Comment by nicolevasilevsky** [comment]
I am speaking to Nico now and he said there is no reason to wait. 

I also added the term to taxon-subset-ids.txt in https://github.com/obophenotype/ncbitaxon/pull/101

**Pull request merged**
