### PR TITLE
Ready for review: revise viral infectious agent classification

### LINKED ISSUE #3203: [NTR] herpesvirus-7 infection
**Preferred term label:**
herpesvirus-7 infection

**Synonyms**
Exact:
HHV-7 infection
PMID:28545483
Abbreviation

**Definition (free text, please give PubMed ID, if applicable, in format PMID:#######)**
A disease caused by infection with herpesvirus-7.
MONDO:patterns/infectious_disease_by_agent
PMID:28545483

**Parent term (use [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo), or your favorite ontology browser)**
roseolovirus infectious disease

### PR DESCRIPTION
**Pull request by nicolevasilevsky**
address #2950 
fix #3203

### CODE REVIEW

**Comment by nicolevasilevsky** [comment]
These classes have single children that are causing the build failure:
image

image

image

**Comment by cmungall** [comment]
> These classes have single children that are causing the build failure:
> image
> 
> image
> 
> image

what do you think we should do? Should we merge? Or are they (discovered or undiscovered) sibs?

**Comment by nicolevasilevsky** [comment]
The classes above no longer have single children after we did further edits.

**Comment by nicolevasilevsky** [comment]
These terms have single children
'orthomyxoviridae infectious disease'
'coxsackievirus infectious disease'
'roseolovirus infectious disease'

**Comment by nicolevasilevsky** [comment]
I think this is ready to merge

**Comment by nicolevasilevsky** [comment]
@cmungall my latest questions:

1. what is the difference between 'viral disease or post-viral disorder' and 'viral infectious disease or sequela'? I think these are the same.
2. 'post-viral disorder' has a synonym of sequela of viral disease, but it doesn't have a dbxref

this is what we currently have

image

should it be like this?
image

**Comment by maglott** [comment]
My question would be the same as Nicole's.  Is there any method to distinguish between nodes that are established only for classification, and nodes that represent names of disorders?

**Comment by nicolevasilevsky** [comment]
@maglott great question - we need to think about how to address this.
@matentzn and I are discussing a workflow to tag classes that are purely used for grouping using a subset tag that is specifically designed for this purpose

**Comment by cmungall** [comment]
I think your proposal makes sense @nicolevasilevsky

**Pull request merged**
