### PR TITLE
Reran `make sssom` and `make mappings`

### PR DESCRIPTION
**Pull request by hrshdhgd**
Commands I ran:

`sh run.sh make sssom`
`sh run.sh make mappings`

### CODE REVIEW

**Comment by joeflack4** [comment]
Sweet, looks like a lot more content here than when I opened a similar PR on `mondo-ingest`. I think I just ran the `make` commands on the wrong repo.

**Comment by nicolevasilevsky** [comment]
@hrshdhgd I think this is fine, but I'm not totally clear what the implications are for this. Does this need to be spot checked to ensure the new mappings are correct?

I'm not totally clear how this relates to this: https://github.com/monarch-initiative/mondo-ingest/issues/78

@sabrinatoro could you also review this and discuss on the tech call if needed?

**Comment by hrshdhgd** [comment]
So when this is merged, I will run the 'mondo-ingest` pipeline which sources the `mondo.sssom.tsv` file from the master branch here. Once this PR is merged, the `mondo-ingest` pipeline can get the latest mapped version as per my understanding. I could redirect it to use the branch version but if the changes look okay, merging it would simplify things.

**Comment by nicolevasilevsky** [comment]
sounds good! I'll go ahead and merge. Thanks Harshad!

**Review by nicolevasilevsky — APPROVED** [review]

**Comment by hrshdhgd** [comment]
Thank you!

**Pull request merged**
